In [1]:
import polars as pl


DATASET_NAME_PERFIX = "dataset_255w_"
TRAIN_SIZE = 0.8
VAL_SIZE = 0.1
TEST_SIZE = 0.1


df_with_parent= pl.read_csv(
    "lehner_dataset_with_sequences_normalized.csv",
    separator=",",
    null_values="NA",
    infer_schema_length=10000
)
df_with_parent = df_with_parent.drop_nulls(subset=["original_sequence", "position", "normalized_fitness_sigma"])

df_with_parent = df_with_parent.drop(["domain_ID", "aa_seq", "input_count_rep1", "input_count_rep2", "input_count_rep3",
                 "output_count_rep1", "output_count_rep2", "output_count_rep3",
                 "mean_input_count", "quality_rank", "fitness", 'fitness_sigma'])

df_with_parent

shape: (1_116_004, 10)
┌────────────┬───────┬──────────┬────────┬───┬──────────────┬──────────────┬─────────┬─────────────┐
│ uniprot_ID ┆ wt_aa ┆ position ┆ mut_aa ┆ … ┆ normalized_f ┆ original_seq ┆ reverse ┆ normalized_ │
│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ itness_sigma ┆ uence        ┆ ---     ┆ fitness_sig │
│ str        ┆ str   ┆ i64      ┆ str    ┆   ┆ ---          ┆ ---          ┆ bool    ┆ moid        │
│            ┆       ┆          ┆        ┆   ┆ f64          ┆ str          ┆         ┆ ---         │
│            ┆       ┆          ┆        ┆   ┆              ┆              ┆         ┆ f64         │
╞════════════╪═══════╪══════════╪════════╪═══╪══════════════╪══════════════╪═════════╪═════════════╡
│ A0A2R8Y422 ┆ *     ┆ 2        ┆ Q      ┆ … ┆ 0.208478     ┆ MQIFVKTLMGKT ┆ true    ┆ 0.36025     │
│            ┆       ┆          ┆        ┆   ┆              ┆ ITLEVELSDTID ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ NVKAKI…      ┆         ┆             │
│ A0A2R8Y422 ┆ A     ┆ 2        ┆ Q      ┆ … ┆ 0.093461     ┆ MQIFVKTLMGKT ┆ true    ┆ 0.128588    │
│            ┆       ┆          ┆        ┆   ┆              ┆ ITLEVELSDTID ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ NVKAKI…      ┆         ┆             │
│ A0A2R8Y422 ┆ C     ┆ 2        ┆ Q      ┆ … ┆ 0.057995     ┆ MQIFVKTLMGKT ┆ true    ┆ 0.047511    │
│            ┆       ┆          ┆        ┆   ┆              ┆ ITLEVELSDTID ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ NVKAKI…      ┆         ┆             │
│ A0A2R8Y422 ┆ D     ┆ 2        ┆ Q      ┆ … ┆ 0.072296     ┆ MQIFVKTLMGKT ┆ true    ┆ 0.118255    │
│            ┆       ┆          ┆        ┆   ┆              ┆ ITLEVELSDTID ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ NVKAKI…      ┆         ┆             │
│ A0A2R8Y422 ┆ E     ┆ 2        ┆ Q      ┆ … ┆ 0.169263     ┆ MQIFVKTLMGKT ┆ true    ┆ -0.086631   │
│            ┆       ┆          ┆        ┆   ┆              ┆ ITLEVELSDTID ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ NVKAKI…      ┆         ┆             │
│ …          ┆ …     ┆ …        ┆ …      ┆ … ┆ …            ┆ …            ┆ …       ┆ …           │
│ Q9Y6V0     ┆ C     ┆ 1059     ┆ V      ┆ … ┆ 0.157535     ┆ MGNEASLEGEGL ┆ false   ┆ -0.251218   │
│            ┆       ┆          ┆        ┆   ┆              ┆ PEGLAAAAAAGG ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ GASGAG…      ┆         ┆             │
│ Q9Y6V0     ┆ C     ┆ 1059     ┆ W      ┆ … ┆ 0.15048      ┆ MGNEASLEGEGL ┆ false   ┆ -0.205368   │
│            ┆       ┆          ┆        ┆   ┆              ┆ PEGLAAAAAAGG ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ GASGAG…      ┆         ┆             │
│ Q9Y6V0     ┆ C     ┆ 1059     ┆ Y      ┆ … ┆ 0.155403     ┆ MGNEASLEGEGL ┆ false   ┆ -0.258928   │
│            ┆       ┆          ┆        ┆   ┆              ┆ PEGLAAAAAAGG ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ GASGAG…      ┆         ┆             │
│ Q9Y6V0     ┆ T     ┆ 1058     ┆ V      ┆ … ┆ 0.246396     ┆ MGNEASLEGEGL ┆ false   ┆ -0.046414   │
│            ┆       ┆          ┆        ┆   ┆              ┆ PEGLAAAAAAGG ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ GASGAG…      ┆         ┆             │
│ Q9Y6V0     ┆ T     ┆ 1058     ┆ W      ┆ … ┆ 0.235147     ┆ MGNEASLEGEGL ┆ false   ┆ -0.118282   │
│            ┆       ┆          ┆        ┆   ┆              ┆ PEGLAAAAAAGG ┆         ┆             │
│            ┆       ┆          ┆        ┆   ┆              ┆ GASGAG…      ┆         ┆             │
└────────────┴───────┴──────────┴────────┴───┴──────────────┴──────────────┴─────────┴─────────────┘

In [2]:
df_with_parent["original_sequence"].str.len_chars().describe()

shape: (9, 2)
┌────────────┬────────────┐
│ statistic  ┆ value      │
│ ---        ┆ ---        │
│ str        ┆ f64        │
╞════════════╪════════════╡
│ count      ┆ 1.116004e6 │
│ null_count ┆ 0.0        │
│ mean       ┆ 911.513955 │
│ std        ┆ 838.009222 │
│ min        ┆ 66.0       │
│ 25%        ┆ 422.0      │
│ 50%        ┆ 683.0      │
│ 75%        ┆ 1099.0     │
│ max        ┆ 8525.0     │
└────────────┴────────────┘

In [3]:
# adding the columns with the fragment of 255 aa around the mutation


# Remove rows with NaN in original_sequence and position
df_127 = df_with_parent.drop_nulls(subset=["original_sequence", "position", "normalized_fitness", "normalized_fitness_sigma"])


# Add sub_sequence column (21 aa from 'position')
df_127 = df_127.with_columns(
    pl.col("original_sequence").str.slice(pl.col("position").cast(pl.Int64), 21).alias("sub_sequence")
)

WINDOW = 255
HALF = WINDOW // 2  # 256

def extract_fragment(seq: str, pos: int, mut_aa=None) -> tuple[str, int]:
    if seq is None or pos is None:
        return None, None

    pos -= 1  # Convert to 0-based index
    seq_len = len(seq)
    # Navrhujeme start/end tak, aby pos byl uprostřed
    start = max(0, pos - HALF)
    end = min(seq_len, start + WINDOW)

    # Pokud na konci nezbyde 512 znaků, posuň začátek zpět
    if end - start < WINDOW:
        start = max(0, end - WINDOW)

    if mut_aa:
        seqlist = list(seq)
        seqlist[pos] = mut_aa
        seq = "".join(seqlist)

    fragment = seq[start:end]
    local_pos = pos - start
    return fragment, local_pos

def position_normilized(seq: str, pos: int) -> int:
    if seq is None or pos is None:
        return None
    pos -= 1  # Convert to 0-based index
    seq_len = len(seq)
    if pos < 0 or pos >= seq_len:
        return None
    return pos/ seq_len

df_127 = df_127.with_columns([
    pl.struct(["original_sequence", "position", "mut_aa"])
      .map_elements(lambda x: extract_fragment(x["original_sequence"], int(x["position"]), x["mut_aa"])[0],
                    return_dtype=pl.Utf8)
      .alias("fragment_255_mut"),

    pl.struct(["original_sequence", "position"])
      .map_elements(lambda x: extract_fragment(x["original_sequence"], int(x["position"]))[1],
                    return_dtype=pl.Int64)
      .alias("local_position"),

    pl.struct(["original_sequence", "position"])
      .map_elements(lambda x: extract_fragment(x["original_sequence"], int(x["position"]))[0],
                    return_dtype=pl.Utf8)
      .alias("fragment_255_org"),

        pl.struct(["original_sequence", "position"])
      .map_elements(lambda x: position_normilized(x["original_sequence"], int(x["position"])),
                    return_dtype=pl.Float32)
      .alias("position_normalized"),
])


df_127 = df_127.drop(["original_sequence", "sub_sequence", "position", "normalized_fitness", "normalized_fitness_sigma"])

df_127

shape: (1_116_004, 10)
┌────────────┬───────┬────────┬───────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ uniprot_ID ┆ wt_aa ┆ mut_aa ┆ STOP  ┆ … ┆ fragment_255 ┆ local_posit ┆ fragment_25 ┆ position_no │
│ ---        ┆ ---   ┆ ---    ┆ ---   ┆   ┆ _mut         ┆ ion         ┆ 5_org       ┆ rmalized    │
│ str        ┆ str   ┆ str    ┆ bool  ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│            ┆       ┆        ┆       ┆   ┆ str          ┆ i64         ┆ str         ┆ f32         │
╞════════════╪═══════╪════════╪═══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ A0A2R8Y422 ┆ *     ┆ Q      ┆ true  ┆ … ┆ MQIFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ A0A2R8Y422 ┆ A     ┆ Q      ┆ false ┆ … ┆ MQIFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ A0A2R8Y422 ┆ C     ┆ Q      ┆ false ┆ … ┆ MQIFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ A0A2R8Y422 ┆ D     ┆ Q      ┆ false ┆ … ┆ MQIFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ A0A2R8Y422 ┆ E     ┆ Q      ┆ false ┆ … ┆ MQIFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ …          ┆ …     ┆ …      ┆ …     ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ Q9Y6V0     ┆ C     ┆ V      ┆ false ┆ … ┆ FGFGASIFSQAS ┆ 127         ┆ FGFGASIFSQA ┆ 0.205757    │
│            ┆       ┆        ┆       ┆   ┆ NLISTAGQPGPH ┆             ┆ SNLISTAGQPG ┆             │
│            ┆       ┆        ┆       ┆   ┆ SQSGPG…      ┆             ┆ PHSQSGPG…   ┆             │
│ Q9Y6V0     ┆ C     ┆ W      ┆ false ┆ … ┆ FGFGASIFSQAS ┆ 127         ┆ FGFGASIFSQA ┆ 0.205757    │
│            ┆       ┆        ┆       ┆   ┆ NLISTAGQPGPH ┆             ┆ SNLISTAGQPG ┆             │
│            ┆       ┆        ┆       ┆   ┆ SQSGPG…      ┆             ┆ PHSQSGPG…   ┆             │
│ Q9Y6V0     ┆ C     ┆ Y      ┆ false ┆ … ┆ FGFGASIFSQAS ┆ 127         ┆ FGFGASIFSQA ┆ 0.205757    │
│            ┆       ┆        ┆       ┆   ┆ NLISTAGQPGPH ┆             ┆ SNLISTAGQPG ┆             │
│            ┆       ┆        ┆       ┆   ┆ SQSGPG…      ┆             ┆ PHSQSGPG…   ┆             │
│ Q9Y6V0     ┆ T     ┆ V      ┆ false ┆ … ┆ LFGFGASIFSQA ┆ 127         ┆ LFGFGASIFSQ ┆ 0.205562    │
│            ┆       ┆        ┆       ┆   ┆ SNLISTAGQPGP ┆             ┆ ASNLISTAGQP ┆             │
│            ┆       ┆        ┆       ┆   ┆ HSQSGP…      ┆             ┆ GPHSQSGP…   ┆             │
│ Q9Y6V0     ┆ T     ┆ W      ┆ false ┆ … ┆ LFGFGASIFSQA ┆ 127         ┆ LFGFGASIFSQ ┆ 0.205562    │
│            ┆       ┆        ┆       ┆   ┆ SNLISTAGQPGP ┆             ┆ ASNLISTAGQP ┆             │
│            ┆       ┆        ┆       ┆   ┆ HSQSGP…      ┆             ┆ GPHSQSGP…   ┆             │
└────────────┴───────┴────────┴───────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [4]:
# First, we shuffle the data randomly
df_shuffled = df_127.sample(fraction=1, shuffle=True, seed=123) # Using a seed for reproducibility

# Get the total number of rows
n_rows = len(df_shuffled)

# Calculate the sizes of each set (80% training, 10% validation, 10% testing)
train_size = int(TRAIN_SIZE * n_rows)
val_size = int(VAL_SIZE * n_rows)
# The remainder will be the testing set

# Split the dataframe into three parts
train_df = df_shuffled.slice(0, train_size)
val_df = df_shuffled.slice(train_size, val_size)
test_df = df_shuffled.slice(train_size + val_size) # to the end

test_df_noreverse = test_df.filter(pl.col("reverse") == False)


# Save each dataset to a separate CSV file
train_df.write_csv(f"{DATASET_NAME_PERFIX}train.csv")
val_df.write_csv(f"{DATASET_NAME_PERFIX}validation.csv")
test_df.write_csv(f"{DATASET_NAME_PERFIX}test.csv")
test_df_noreverse.write_csv(f"{DATASET_NAME_PERFIX}_noreverse_test.csv")

print(f"Datasets were successfully created and saved:")
print(f"- Training set (training_dataset.csv): {len(train_df)} rows")
print(f"- Validation set (validation_dataset.csv): {len(val_df)} rows")
print(f"- Testing set (testing_dataset.csv): {len(test_df)} rows")
print(f"- Testing set without reverse mutations (testing_noreverse_dataset.csv): {len(test_df_noreverse)} rows")

Datasets were successfully created and saved:
- Training set (training_dataset.csv): 892803 rows
- Validation set (validation_dataset.csv): 111600 rows
- Testing set (testing_dataset.csv): 111601 rows
- Testing set without reverse mutations (testing_noreverse_dataset.csv): 55760 rows

In [18]:
train_df

shape: (892_803, 10)
┌────────────┬───────┬────────┬───────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ uniprot_ID ┆ wt_aa ┆ mut_aa ┆ STOP  ┆ … ┆ fragment_255 ┆ local_posit ┆ fragment_25 ┆ position_no │
│ ---        ┆ ---   ┆ ---    ┆ ---   ┆   ┆ _mut         ┆ ion         ┆ 5_org       ┆ rmalized    │
│ str        ┆ str   ┆ str    ┆ bool  ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│            ┆       ┆        ┆       ┆   ┆ str          ┆ i64         ┆ str         ┆ f32         │
╞════════════╪═══════╪════════╪═══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ P48431     ┆ *     ┆ K      ┆ true  ┆ … ┆ MYNMMETELKPP ┆ 79          ┆ MYNMMETELKP ┆ 0.249211    │
│            ┆       ┆        ┆       ┆   ┆ GPQQTSGGGGGN ┆             ┆ PGPQQTSGGGG ┆             │
│            ┆       ┆        ┆       ┆   ┆ STAAAA…      ┆             ┆ GNSTAAAA…   ┆             │
│ Q13009     ┆ M     ┆ D      ┆ false ┆ … ┆ TARDTLELICKT ┆ 127         ┆ TARDTLELICK ┆ 0.573224    │
│            ┆       ┆        ┆       ┆   ┆ HQLDHSAHYLRL ┆             ┆ THQLDHSAHYL ┆             │
│            ┆       ┆        ┆       ┆   ┆ KFLIEN…      ┆             ┆ RLKFLIEN…   ┆             │
│ P46937     ┆ K     ┆ G      ┆ false ┆ … ┆ SHSRQASTDAGT ┆ 127         ┆ SHSRQASTDAG ┆ 0.454365    │
│            ┆       ┆        ┆       ┆   ┆ AGALTPQHVRAH ┆             ┆ TAGALTPQHVR ┆             │
│            ┆       ┆        ┆       ┆   ┆ SSPASL…      ┆             ┆ AHSSPASL…   ┆             │
│ Q9Y5K6     ┆ P     ┆ R      ┆ false ┆ … ┆ MVDYIVEYDYDA ┆ 58          ┆ MVDYIVEYDYD ┆ 0.090767    │
│            ┆       ┆        ┆       ┆   ┆ VHDDELTIRVGE ┆             ┆ AVHDDELTIRV ┆             │
│            ┆       ┆        ┆       ┆   ┆ IIRNVK…      ┆             ┆ GEIIRNVK…   ┆             │
│ P10242     ┆ L     ┆ T      ┆ false ┆ … ┆ KLKKLVEQNGTD ┆ 127         ┆ KLKKLVEQNGT ┆ 0.275       │
│            ┆       ┆        ┆       ┆   ┆ DWKVIANYLPNR ┆             ┆ DDWKVIANYLP ┆             │
│            ┆       ┆        ┆       ┆   ┆ TDVQCQ…      ┆             ┆ NRTDVQCQ…   ┆             │
│ …          ┆ …     ┆ …      ┆ …     ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ P25685     ┆ V     ┆ S      ┆ false ┆ … ┆ MGKDYYQTLGLA ┆ 55          ┆ MGKDYYQTLGL ┆ 0.161765    │
│            ┆       ┆        ┆       ┆   ┆ RGASDEEIKRAY ┆             ┆ ARGASDEEIKR ┆             │
│            ┆       ┆        ┆       ┆   ┆ RRQALR…      ┆             ┆ AYRRQALR…   ┆             │
│ O15405     ┆ R     ┆ G      ┆ false ┆ … ┆ PPAQLTTINQSQ ┆ 127         ┆ PPAQLTTINQS ┆ 0.513889    │
│            ┆       ┆        ┆       ┆   ┆ LSAQLGLNLGGA ┆             ┆ QLSAQLGLNLG ┆             │
│            ┆       ┆        ┆       ┆   ┆ SMPHTS…      ┆             ┆ GASMPHTS…   ┆             │
│ Q13501     ┆ K     ┆ D      ┆ false ┆ … ┆ RKVKHGHFGWPG ┆ 237         ┆ RKVKHGHFGWP ┆ 0.959091    │
│            ┆       ┆        ┆       ┆   ┆ WEMGPPGNWSPR ┆             ┆ GWEMGPPGNWS ┆             │
│            ┆       ┆        ┆       ┆   ┆ PPRAGE…      ┆             ┆ PRPPRAGE…   ┆             │
│ Q9BY11     ┆ L     ┆ Y      ┆ false ┆ … ┆ KLQDKVDKCKQD ┆ 206         ┆ KLQDKVDKCKQ ┆ 0.88964     │
│            ┆       ┆        ┆       ┆   ┆ VQKTQEKYEKVL ┆             ┆ DVQKTQEKYEK ┆             │
│            ┆       ┆        ┆       ┆   ┆ EDVGKT…      ┆             ┆ VLEDVGKT…   ┆             │
│ Q14202     ┆ A     ┆ F      ┆ false ┆ … ┆ SLFCSLCCTTSY ┆ 127         ┆ SLFCSLCCTTS ┆ 0.472263    │
│            ┆       ┆        ┆       ┆   ┆ KVKQAGLTGPPR ┆             ┆ YKVKQAGLTGP ┆             │
│            ┆       ┆        ┆       ┆   ┆ PCSFCR…      ┆             ┆ PRPCSFCR…   ┆             │
└────────────┴───────┴────────┴───────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘