In [6]:
import polars as pl


DATASET_NAME_PERFIX = "dataset_255w_"
TRAIN_SIZE = 0.8
VAL_SIZE = 0.1
TEST_SIZE = 0.1


df_with_parent= pl.read_csv(
    "lehner_dataset_with_sequences.csv",
    separator=",",
    null_values="NA",
    infer_schema_length=10000
)
df_with_parent = df_with_parent.drop_nulls(subset=["original_sequence", "position", "normalized_fitness", "normalized_fitness_sigma"])

df_with_parent = df_with_parent.drop(["domain_ID", "aa_seq", "input_count_rep1", "input_count_rep2", "input_count_rep3",
                 "output_count_rep1", "output_count_rep2", "output_count_rep3",
                 "mean_input_count", "quality_rank", "fitness", 'fitness_sigma'])

df_with_parent

shape: (560_668, 12)
┌────────────┬───────┬──────────┬────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ uniprot_ID ┆ wt_aa ┆ position ┆ mut_aa ┆ … ┆ normalized_ ┆ normalized_ ┆ normalized ┆ normalized │
│ ---        ┆ ---   ┆ ---      ┆ ---    ┆   ┆ fitness_tra ┆ fitness_tra ┆ _fitness_t ┆ _fitness_a │
│ str        ┆ str   ┆ i64      ┆ str    ┆   ┆ ining       ┆ ining_si…   ┆ raining_ta ┆ symmetric  │
│            ┆       ┆          ┆        ┆   ┆ ---         ┆ ---         ┆ …          ┆ ---        │
│            ┆       ┆          ┆        ┆   ┆ f64         ┆ f64         ┆ ---        ┆ f64        │
│            ┆       ┆          ┆        ┆   ┆             ┆             ┆ f64        ┆            │
╞════════════╪═══════╪══════════╪════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ A0A2R8Y422 ┆ Q     ┆ 2        ┆ *      ┆ … ┆ -0.081722   ┆ -0.081722   ┆ -0.102025  ┆ -0.530676  │
│ A0A2R8Y422 ┆ Q     ┆ 2        ┆ A      ┆ … ┆ -0.028072   ┆ -0.028072   ┆ -0.035084  ┆ -0.510528  │
│ A0A2R8Y422 ┆ Q     ┆ 2        ┆ C      ┆ … ┆ -0.010325   ┆ -0.010325   ┆ -0.012906  ┆ -0.503872  │
│ A0A2R8Y422 ┆ Q     ┆ 2        ┆ D      ┆ … ┆ -0.025795   ┆ -0.025795   ┆ -0.032239  ┆ -0.509674  │
│ A0A2R8Y422 ┆ Q     ┆ 2        ┆ E      ┆ … ┆ 0.03766     ┆ 0.03766     ┆ 0.047063   ┆ 0.528229   │
│ …          ┆ …     ┆ …        ┆ …      ┆ … ┆ …           ┆ …           ┆ …          ┆ …          │
│ Q9Y6V0     ┆ C     ┆ 1059     ┆ V      ┆ … ┆ -0.110914   ┆ -0.110914   ┆ -0.138323  ┆ -0.541668  │
│ Q9Y6V0     ┆ C     ┆ 1059     ┆ W      ┆ … ┆ -0.090137   ┆ -0.090137   ┆ -0.112499  ┆ -0.533841  │
│ Q9Y6V0     ┆ C     ┆ 1059     ┆ Y      ┆ … ┆ -0.114446   ┆ -0.114446   ┆ -0.142706  ┆ -0.543     │
│ Q9Y6V0     ┆ T     ┆ 1058     ┆ V      ┆ … ┆ -0.020148   ┆ -0.020148   ┆ -0.025183  ┆ -0.507556  │
│ Q9Y6V0     ┆ T     ┆ 1058     ┆ W      ┆ … ┆ -0.051511   ┆ -0.051511   ┆ -0.064357  ┆ -0.519324  │
└────────────┴───────┴──────────┴────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

In [2]:
df_with_parent["normalized_fitness_training"].describe()

shape: (9, 2)
┌────────────┬───────────┐
│ statistic  ┆ value     │
│ ---        ┆ ---       │
│ str        ┆ f64       │
╞════════════╪═══════════╡
│ count      ┆ 560668.0  │
│ null_count ┆ 0.0       │
│ mean       ┆ -0.031822 │
│ std        ┆ 0.038346  │
│ min        ┆ -0.485193 │
│ 25%        ┆ -0.057357 │
│ 50%        ┆ -0.021016 │
│ 75%        ┆ -0.003941 │
│ max        ┆ 0.202422  │
└────────────┴───────────┘

In [3]:



# Remove rows with NaN in original_sequence and position
df_127 = df_with_parent.drop_nulls(subset=["original_sequence", "position", "normalized_fitness", "normalized_fitness_sigma"])


# Add sub_sequence column (21 aa from 'position')
df_127 = df_127.with_columns(
    pl.col("original_sequence").str.slice(pl.col("position").cast(pl.Int64), 21).alias("sub_sequence")
)

WINDOW = 255
HALF = WINDOW // 2  # 256

def extract_fragment(seq: str, pos: int, mut_aa=None) -> tuple[str, int]:
    if seq is None or pos is None:
        return None, None

    pos -= 1  # Convert to 0-based index
    seq_len = len(seq)
    # Navrhujeme start/end tak, aby pos byl uprostřed
    start = max(0, pos - HALF)
    end = min(seq_len, start + WINDOW)

    # Pokud na konci nezbyde 512 znaků, posuň začátek zpět
    if end - start < WINDOW:
        start = max(0, end - WINDOW)

    if mut_aa:
        seqlist = list(seq)
        seqlist[pos] = mut_aa
        seq = "".join(seqlist)

    fragment = seq[start:end]
    local_pos = pos - start
    return fragment, local_pos

def position_normilized(seq: str, pos: int) -> int:
    if seq is None or pos is None:
        return None
    pos -= 1  # Convert to 0-based index
    seq_len = len(seq)
    if pos < 0 or pos >= seq_len:
        return None
    return pos/ seq_len

df_127 = df_127.with_columns([
    pl.struct(["original_sequence", "position", "mut_aa"])
      .map_elements(lambda x: extract_fragment(x["original_sequence"], int(x["position"]), x["mut_aa"])[0],
                    return_dtype=pl.Utf8)
      .alias("fragment_255_mut"),

    pl.struct(["original_sequence", "position"])
      .map_elements(lambda x: extract_fragment(x["original_sequence"], int(x["position"]))[1],
                    return_dtype=pl.Int64)
      .alias("local_position"),

    pl.struct(["original_sequence", "position"])
      .map_elements(lambda x: extract_fragment(x["original_sequence"], int(x["position"]))[0],
                    return_dtype=pl.Utf8)
      .alias("fragment_255_org"),

        pl.struct(["original_sequence", "position"])
      .map_elements(lambda x: position_normilized(x["original_sequence"], int(x["position"])),
                    return_dtype=pl.Float32)
      .alias("position_normilized"),
])


df_127 = df_127.drop(["original_sequence", "sub_sequence", "position"])

df_127

shape: (560_668, 14)
┌────────────┬───────┬────────┬───────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ uniprot_ID ┆ wt_aa ┆ mut_aa ┆ STOP  ┆ … ┆ fragment_255 ┆ local_posit ┆ fragment_25 ┆ position_no │
│ ---        ┆ ---   ┆ ---    ┆ ---   ┆   ┆ _mut         ┆ ion         ┆ 5_org       ┆ rmilized    │
│ str        ┆ str   ┆ str    ┆ bool  ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│            ┆       ┆        ┆       ┆   ┆ str          ┆ i64         ┆ str         ┆ f32         │
╞════════════╪═══════╪════════╪═══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ A0A2R8Y422 ┆ Q     ┆ *      ┆ true  ┆ … ┆ M*IFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ A0A2R8Y422 ┆ Q     ┆ A      ┆ false ┆ … ┆ MAIFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ A0A2R8Y422 ┆ Q     ┆ C      ┆ false ┆ … ┆ MCIFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ A0A2R8Y422 ┆ Q     ┆ D      ┆ false ┆ … ┆ MDIFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ A0A2R8Y422 ┆ Q     ┆ E      ┆ false ┆ … ┆ MEIFVKTLMGKT ┆ 1           ┆ MQIFVKTLMGK ┆ 0.00641     │
│            ┆       ┆        ┆       ┆   ┆ ITLEVELSDTID ┆             ┆ TITLEVELSDT ┆             │
│            ┆       ┆        ┆       ┆   ┆ NVKAKI…      ┆             ┆ IDNVKAKI…   ┆             │
│ …          ┆ …     ┆ …      ┆ …     ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ Q9Y6V0     ┆ C     ┆ V      ┆ false ┆ … ┆ FGFGASIFSQAS ┆ 127         ┆ FGFGASIFSQA ┆ 0.205757    │
│            ┆       ┆        ┆       ┆   ┆ NLISTAGQPGPH ┆             ┆ SNLISTAGQPG ┆             │
│            ┆       ┆        ┆       ┆   ┆ SQSGPG…      ┆             ┆ PHSQSGPG…   ┆             │
│ Q9Y6V0     ┆ C     ┆ W      ┆ false ┆ … ┆ FGFGASIFSQAS ┆ 127         ┆ FGFGASIFSQA ┆ 0.205757    │
│            ┆       ┆        ┆       ┆   ┆ NLISTAGQPGPH ┆             ┆ SNLISTAGQPG ┆             │
│            ┆       ┆        ┆       ┆   ┆ SQSGPG…      ┆             ┆ PHSQSGPG…   ┆             │
│ Q9Y6V0     ┆ C     ┆ Y      ┆ false ┆ … ┆ FGFGASIFSQAS ┆ 127         ┆ FGFGASIFSQA ┆ 0.205757    │
│            ┆       ┆        ┆       ┆   ┆ NLISTAGQPGPH ┆             ┆ SNLISTAGQPG ┆             │
│            ┆       ┆        ┆       ┆   ┆ SQSGPG…      ┆             ┆ PHSQSGPG…   ┆             │
│ Q9Y6V0     ┆ T     ┆ V      ┆ false ┆ … ┆ LFGFGASIFSQA ┆ 127         ┆ LFGFGASIFSQ ┆ 0.205562    │
│            ┆       ┆        ┆       ┆   ┆ SNLISTAGQPGP ┆             ┆ ASNLISTAGQP ┆             │
│            ┆       ┆        ┆       ┆   ┆ HSQSGP…      ┆             ┆ GPHSQSGP…   ┆             │
│ Q9Y6V0     ┆ T     ┆ W      ┆ false ┆ … ┆ LFGFGASIFSQA ┆ 127         ┆ LFGFGASIFSQ ┆ 0.205562    │
│            ┆       ┆        ┆       ┆   ┆ SNLISTAGQPGP ┆             ┆ ASNLISTAGQP ┆             │
│            ┆       ┆        ┆       ┆   ┆ HSQSGP…      ┆             ┆ GPHSQSGP…   ┆             │
└────────────┴───────┴────────┴───────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘

In [4]:
# First, we shuffle the data randomly
df_shuffled = df_127.sample(fraction=1, shuffle=True, seed=42) # Using a seed for reproducibility

# Get the total number of rows
n_rows = len(df_shuffled)

# Calculate the sizes of each set (80% training, 10% validation, 10% testing)
train_size = int(TRAIN_SIZE * n_rows)
val_size = int(VAL_SIZE * n_rows)
# The remainder will be the testing set

# Split the dataframe into three parts
train_df = df_shuffled.slice(0, train_size)
val_df = df_shuffled.slice(train_size, val_size)
test_df = df_shuffled.slice(train_size + val_size) # to the end


# Save each dataset to a separate CSV file
train_df.write_csv(f"{DATASET_NAME_PERFIX}train.csv")
val_df.write_csv(f"{DATASET_NAME_PERFIX}validation.csv")
test_df.write_csv(f"{DATASET_NAME_PERFIX}test.csv")

print(f"Datasets were successfully created and saved:")
print(f"- Training set (training_dataset.csv): {len(train_df)} rows")
print(f"- Validation set (validation_dataset.csv): {len(val_df)} rows")
print(f"- Testing set (testing_dataset.csv): {len(test_df)} rows")

Datasets were successfully created and saved:
- Training set (training_dataset.csv): 448534 rows
- Validation set (validation_dataset.csv): 56066 rows
- Testing set (testing_dataset.csv): 56068 rows

In [5]:
train_df

shape: (448_534, 14)
┌────────────┬───────┬────────┬───────┬───┬──────────────┬─────────────┬─────────────┬─────────────┐
│ uniprot_ID ┆ wt_aa ┆ mut_aa ┆ STOP  ┆ … ┆ fragment_255 ┆ local_posit ┆ fragment_25 ┆ position_no │
│ ---        ┆ ---   ┆ ---    ┆ ---   ┆   ┆ _mut         ┆ ion         ┆ 5_org       ┆ rmilized    │
│ str        ┆ str   ┆ str    ┆ bool  ┆   ┆ ---          ┆ ---         ┆ ---         ┆ ---         │
│            ┆       ┆        ┆       ┆   ┆ str          ┆ i64         ┆ str         ┆ f32         │
╞════════════╪═══════╪════════╪═══════╪═══╪══════════════╪═════════════╪═════════════╪═════════════╡
│ Q14839     ┆ C     ┆ *      ┆ true  ┆ … ┆ KPKKVAPLKIKL ┆ 127         ┆ KPKKVAPLKIK ┆ 0.216004    │
│            ┆       ┆        ┆       ┆   ┆ GGFGSKRKRSSS ┆             ┆ LGGFGSKRKRS ┆             │
│            ┆       ┆        ┆       ┆   ┆ EDDDLD…      ┆             ┆ SSEDDDLD…   ┆             │
│ P13796     ┆ K     ┆ D      ┆ false ┆ … ┆ MARGSVSDEEMM ┆ 81          ┆ MARGSVSDEEM ┆ 0.129187    │
│            ┆       ┆        ┆       ┆   ┆ ELREAFAKVDTD ┆             ┆ MELREAFAKVD ┆             │
│            ┆       ┆        ┆       ┆   ┆ GNGYIS…      ┆             ┆ TDGNGYIS…   ┆             │
│ Q13642     ┆ D     ┆ S      ┆ false ┆ … ┆ AKCLHPLANETF ┆ 142         ┆ AKCLHPLANET ┆ 0.650155    │
│            ┆       ┆        ┆       ┆   ┆ VAKDNKILCNKC ┆             ┆ FVAKDNKILCN ┆             │
│            ┆       ┆        ┆       ┆   ┆ TTREDS…      ┆             ┆ KCTTREDS…   ┆             │
│ Q9BZM3     ┆ W     ┆ C      ┆ false ┆ … ┆ CPSRKSGAFCVC ┆ 199         ┆ CPSRKSGAFCV ┆ 0.815789    │
│            ┆       ┆        ┆       ┆   ┆ PLCVTSHLHSSR ┆             ┆ CPLCVTSHLHS ┆             │
│            ┆       ┆        ┆       ┆   ┆ GSVGAG…      ┆             ┆ SRGSVGAG…   ┆             │
│ P50539     ┆ H     ┆ M      ┆ false ┆ … ┆ MERVKMINVQRL ┆ 102         ┆ MERVKMINVQR ┆ 0.447368    │
│            ┆       ┆        ┆       ┆   ┆ LEAAEFLERRER ┆             ┆ LLEAAEFLERR ┆             │
│            ┆       ┆        ┆       ┆   ┆ ECEHGY…      ┆             ┆ ERECEHGY…   ┆             │
│ …          ┆ …     ┆ …      ┆ …     ┆ … ┆ …            ┆ …           ┆ …           ┆ …           │
│ O94885     ┆ I     ┆ P      ┆ false ┆ … ┆ QSSMSGQTVSTT ┆ 127         ┆ QSSMSGQTVST ┆ 0.516439    │
│            ┆       ┆        ┆       ┆   ┆ DSSTSNRESVKS ┆             ┆ TDSSTSNRESV ┆             │
│            ┆       ┆        ┆       ┆   ┆ EDGDDE…      ┆             ┆ KSEDGDDE…   ┆             │
│ O43167     ┆ K     ┆ F      ┆ false ┆ … ┆ ERPFKCNECGKG ┆ 127         ┆ ERPFKCNECGK ┆ 0.638451    │
│            ┆       ┆        ┆       ┆   ┆ FAQKHSLQVHTR ┆             ┆ GFAQKHSLQVH ┆             │
│            ┆       ┆        ┆       ┆   ┆ MHTGER…      ┆             ┆ TRMHTGER…   ┆             │
│ P07814     ┆ K     ┆ C      ┆ false ┆ … ┆ PSLNNNCTTSED ┆ 127         ┆ PSLNNNCTTSE ┆ 0.571429    │
│            ┆       ┆        ┆       ┆   ┆ SLVLYNRVAVQG ┆             ┆ DSLVLYNRVAV ┆             │
│            ┆       ┆        ┆       ┆   ┆ DVVREL…      ┆             ┆ QGDVVREL…   ┆             │
│ Q68CP9     ┆ V     ┆ Q      ┆ false ┆ … ┆ SSSHQMLSEIRP ┆ 127         ┆ SSSHQMLSEIR ┆ 0.325886    │
│            ┆       ┆        ┆       ┆   ┆ QAIEQVQTQTHV ┆             ┆ PQAIEQVQTQT ┆             │
│            ┆       ┆        ┆       ┆   ┆ ASAPAS…      ┆             ┆ HVASAPAS…   ┆             │
│ Q06546     ┆ K     ┆ P      ┆ false ┆ … ┆ DPERSLFDQGVK ┆ 127         ┆ DPERSLFDQGV ┆ 0.444934    │
│            ┆       ┆        ┆       ┆   ┆ TDGTVQLSVQVI ┆             ┆ KTDGTVQLSVQ ┆             │
│            ┆       ┆        ┆       ┆   ┆ SYQGIE…      ┆             ┆ VISYQGIE…   ┆             │
└────────────┴───────┴────────┴───────┴───┴──────────────┴─────────────┴─────────────┴─────────────┘