In [1]:
import polars as pl

df = pl.read_csv(
    "../data/megascale.csv",
    null_values=["NA"],
    infer_schema_length=10000
)

columns_to_convert = ['dG_ML', 'ddG_ML']

df = df.with_columns(
    pl.col(columns_to_convert)
    .str.replace_all(r"[^0-9.-]", "")
    .cast(pl.Float64, strict=False)
)

df = df.select([
    "WT_name",
    "name",
    "deltaG",
    "mut_type",
    "aa_seq",
    "aa_seq_full",
])

df = df.rename(
    {
        'aa_seq': 'mutated_seq_short',
        'aa_seq_full': 'mutated_seq_full'
    })

df

shape: (776_298, 6)
┌──────────────────┬──────────────────┬───────────┬───────────┬──────────────────┬─────────────────┐
│ WT_name          ┆ name             ┆ deltaG    ┆ mut_type  ┆ mutated_seq_shor ┆ mutated_seq_ful │
│ ---              ┆ ---              ┆ ---       ┆ ---       ┆ t                ┆ l               │
│ str              ┆ str              ┆ f64       ┆ str       ┆ ---              ┆ ---             │
│                  ┆                  ┆           ┆           ┆ str              ┆ str             │
╞══════════════════╪══════════════════╪═══════════╪═══════════╪══════════════════╪═════════════════╡
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 3.332126  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEV │
│ 5.pdb            ┆ 5.pdb            ┆           ┆           ┆ LDKELLEILKELAR…  ┆ TIHLGDKTIRVDGLD │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 3.399832  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEV │
│ 5.pdb            ┆ 5.pdb_wtm        ┆           ┆           ┆ LDKELLEILKELAR…  ┆ TIHLGDKTIRVDGLD │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 3.315782  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEV │
│ 5.pdb            ┆ 5.pdb_wte        ┆           ┆           ┆ LDKELLEILKELAR…  ┆ TIHLGDKTIRVDGLD │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 3.272933  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEV │
│ 5.pdb            ┆ 5.pdb_wty        ┆           ┆           ┆ LDKELLEILKELAR…  ┆ TIHLGDKTIRVDGLD │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 2.570242  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGSAG │
│ 5.pdb            ┆ 5.pdb_wth        ┆           ┆           ┆ LDKELLEILKELAR…  ┆ GDEVTIHLGDKTIRV │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ …                ┆ …                ┆ …         ┆ …         ┆ …                ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -2.85014  ┆ I32P:L40I ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -3.924992 ┆ I32P:L40W ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -2.365774 ┆ I32P:L40Y ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -1.961486 ┆ I32P:L40F ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -2.050294 ┆ I32P:L40P ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
└──────────────────┴──────────────────┴───────────┴───────────┴──────────────────┴─────────────────┘

In [2]:
import polars as pl
import re
import polars as pl

df_not_wt = df.filter(pl.col('mut_type') != "wt")

MUTATION_REGEX = re.compile(r"([A-Z])(\d+)([A-Z])")

def reconstruct_original_sequence(
    mutated_seq_short: str,
    mut_type: str,
    mutated_seq_full: str
) -> str:
    if not mut_type or "wt" in mut_type.lower():
        return "-"

    index_offset = mutated_seq_full.find(mutated_seq_short)
    if index_offset == -1:
        return "-"

    mutations = mut_type.split(":")
    reverted_seq = mutated_seq_full


    for mutation in mutations:
        match = MUTATION_REGEX.match(mutation)
        if not match:
            # Formát mutace je neplatný
            return "-"

        original_aa, position_str, mutated_aa = match.groups() # Novou (mutovanou) AMK nepotřebujeme

        if original_aa == mutated_aa:
            continue
        position = int(position_str)

        # Výpočet absolutního 0-based indexu v plné sekvenci
        # pozice - 1 (pro 0-based index) + posun
        absolute_index = position - 1 + index_offset

        # Ošetření, pokud je index mimo platný rozsah sekvence
        if not (0 <= absolute_index < len(reverted_seq)):
            return "-"

        # Provedení reverze: na daném indexu nahradíme aminokyselinu tou původní.
        reverted_seq = (
            reverted_seq[:absolute_index] +
            original_aa +
            reverted_seq[absolute_index + 1:]
        )

    if reverted_seq == mutated_seq_full:
        return "-"
    return reverted_seq


df_not_wt = df_not_wt.with_columns(
    pl.struct(['mut_type', 'mutated_seq_full', "mutated_seq_short"])
    .map_elements(
        lambda row: reconstruct_original_sequence(row['mutated_seq_short'], row['mut_type'], row['mutated_seq_full']),
        return_dtype=pl.String)
    # Výsledek uložíme do nového sloupce 'mutated_seq'
    .alias('original_seq_full'),

)

df_not_wt = df_not_wt.select(['name', 'WT_name', 'mut_type', 'mutated_seq_full', 'original_seq_full', "deltaG", "mutated_seq_short"])

# Přejmenování sloupce 'aa_seq' pro lepší srozumitelnost

df_not_wt

shape: (773_950, 7)
┌──────────────┬──────────────┬───────────┬──────────────┬──────────────┬───────────┬──────────────┐
│ name         ┆ WT_name      ┆ mut_type  ┆ mutated_seq_ ┆ original_seq ┆ deltaG    ┆ mutated_seq_ │
│ ---          ┆ ---          ┆ ---       ┆ full         ┆ _full        ┆ ---       ┆ short        │
│ str          ┆ str          ┆ str       ┆ ---          ┆ ---          ┆ f64       ┆ ---          │
│              ┆              ┆           ┆ str          ┆ str          ┆           ┆ str          │
╞══════════════╪══════════════╪═══════════╪══════════════╪══════════════╪═══════════╪══════════════╡
│ EA|run2_0325 ┆ EA|run2_0325 ┆ D1Q       ┆ SAGGSAGGSAGG ┆ SAGGSAGGSAGG ┆ 3.242632  ┆ QEVTIHLGDKTI │
│ _0005.pdb_D1 ┆ _0005.pdb    ┆           ┆ QEVTIHLGDKTI ┆ DEVTIHLGDKTI ┆           ┆ RVDGLDKELLEI │
│ Q            ┆              ┆           ┆ RVDGLD…      ┆ RVDGLD…      ┆           ┆ LKELAR…      │
│ EA|run2_0325 ┆ EA|run2_0325 ┆ D1E       ┆ SAGGSAGGSAGG ┆ SAGGSAGGSAGG ┆ 3.247267  ┆ EEVTIHLGDKTI │
│ _0005.pdb_D1 ┆ _0005.pdb    ┆           ┆ EEVTIHLGDKTI ┆ DEVTIHLGDKTI ┆           ┆ RVDGLDKELLEI │
│ E            ┆              ┆           ┆ RVDGLD…      ┆ RVDGLD…      ┆           ┆ LKELAR…      │
│ EA|run2_0325 ┆ EA|run2_0325 ┆ D1N       ┆ SAGGSAGGSAGG ┆ SAGGSAGGSAGG ┆ 3.269113  ┆ NEVTIHLGDKTI │
│ _0005.pdb_D1 ┆ _0005.pdb    ┆           ┆ NEVTIHLGDKTI ┆ DEVTIHLGDKTI ┆           ┆ RVDGLDKELLEI │
│ N            ┆              ┆           ┆ RVDGLD…      ┆ RVDGLD…      ┆           ┆ LKELAR…      │
│ EA|run2_0325 ┆ EA|run2_0325 ┆ D1H       ┆ SAGGSAGGSAGG ┆ SAGGSAGGSAGG ┆ 3.234823  ┆ HEVTIHLGDKTI │
│ _0005.pdb_D1 ┆ _0005.pdb    ┆           ┆ HEVTIHLGDKTI ┆ DEVTIHLGDKTI ┆           ┆ RVDGLDKELLEI │
│ H            ┆              ┆           ┆ RVDGLD…      ┆ RVDGLD…      ┆           ┆ LKELAR…      │
│ EA|run2_0325 ┆ EA|run2_0325 ┆ D1R       ┆ SAGGSAGGSAGG ┆ SAGGSAGGSAGG ┆ 2.912039  ┆ REVTIHLGDKTI │
│ _0005.pdb_D1 ┆ _0005.pdb    ┆           ┆ REVTIHLGDKTI ┆ DEVTIHLGDKTI ┆           ┆ RVDGLDKELLEI │
│ R            ┆              ┆           ┆ RVDGLD…      ┆ RVDGLD…      ┆           ┆ LKELAR…      │
│ …            ┆ …            ┆ …         ┆ …            ┆ …            ┆ …         ┆ …            │
│ 9AME.pdb_dmu ┆ 9AME.pdb     ┆ I32P:L40I ┆ SAGGSAGGNQAS ┆ SAGGSAGGNQAS ┆ -2.85014  ┆ NQASVVANQLIP │
│ tv5_32I:40L_ ┆              ┆           ┆ VVANQLIPINTA ┆ VVANQLIPINTA ┆           ┆ INTALTLVMMRS │
│ I32P:L…      ┆              ┆           ┆ LTLVMM…      ┆ LTLVMM…      ┆           ┆ EVVTPV…      │
│ 9AME.pdb_dmu ┆ 9AME.pdb     ┆ I32P:L40W ┆ SAGGSAGGNQAS ┆ SAGGSAGGNQAS ┆ -3.924992 ┆ NQASVVANQLIP │
│ tv5_32I:40L_ ┆              ┆           ┆ VVANQLIPINTA ┆ VVANQLIPINTA ┆           ┆ INTALTLVMMRS │
│ I32P:L…      ┆              ┆           ┆ LTLVMM…      ┆ LTLVMM…      ┆           ┆ EVVTPV…      │
│ 9AME.pdb_dmu ┆ 9AME.pdb     ┆ I32P:L40Y ┆ SAGGSAGGNQAS ┆ SAGGSAGGNQAS ┆ -2.365774 ┆ NQASVVANQLIP │
│ tv5_32I:40L_ ┆              ┆           ┆ VVANQLIPINTA ┆ VVANQLIPINTA ┆           ┆ INTALTLVMMRS │
│ I32P:L…      ┆              ┆           ┆ LTLVMM…      ┆ LTLVMM…      ┆           ┆ EVVTPV…      │
│ 9AME.pdb_dmu ┆ 9AME.pdb     ┆ I32P:L40F ┆ SAGGSAGGNQAS ┆ SAGGSAGGNQAS ┆ -1.961486 ┆ NQASVVANQLIP │
│ tv5_32I:40L_ ┆              ┆           ┆ VVANQLIPINTA ┆ VVANQLIPINTA ┆           ┆ INTALTLVMMRS │
│ I32P:L…      ┆              ┆           ┆ LTLVMM…      ┆ LTLVMM…      ┆           ┆ EVVTPV…      │
│ 9AME.pdb_dmu ┆ 9AME.pdb     ┆ I32P:L40P ┆ SAGGSAGGNQAS ┆ SAGGSAGGNQAS ┆ -2.050294 ┆ NQASVVANQLIP │
│ tv5_32I:40L_ ┆              ┆           ┆ VVANQLIPINTA ┆ VVANQLIPINTA ┆           ┆ INTALTLVMMRS │
│ I32P:L…      ┆              ┆           ┆ LTLVMM…      ┆ LTLVMM…      ┆           ┆ EVVTPV…      │
└──────────────┴──────────────┴───────────┴──────────────┴──────────────┴───────────┴──────────────┘

In [3]:
df_wt = df.filter(pl.col('name') == pl.col('WT_name')).filter(pl.col('mut_type') == 'wt')
df_wt

shape: (477, 6)
┌───────────────────┬──────────────────┬──────────┬──────────┬──────────────────┬──────────────────┐
│ WT_name           ┆ name             ┆ deltaG   ┆ mut_type ┆ mutated_seq_shor ┆ mutated_seq_full │
│ ---               ┆ ---              ┆ ---      ┆ ---      ┆ t                ┆ ---              │
│ str               ┆ str              ┆ f64      ┆ str      ┆ ---              ┆ str              │
│                   ┆                  ┆          ┆          ┆ str              ┆                  │
╞═══════════════════╪══════════════════╪══════════╪══════════╪══════════════════╪══════════════════╡
│ EA|run2_0325_0005 ┆ EA|run2_0325_000 ┆ 3.332126 ┆ wt       ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEVT │
│ .pdb              ┆ 5.pdb            ┆          ┆          ┆ LDKELLEILKELAR…  ┆ IHLGDKTIRVDGLD…  │
│ EA|run3_0321_0005 ┆ EA|run3_0321_000 ┆ 3.322303 ┆ wt       ┆ HDVTIHAGDKTIHVHG ┆ SAGGSAGGSAGGHDVT │
│ .pdb              ┆ 5.pdb            ┆          ┆          ┆ ASEEFLRIIEQAKR…  ┆ IHAGDKTIHVHGAS…  │
│ EA|run3_0525_0006 ┆ EA|run3_0525_000 ┆ 3.717377 ┆ wt       ┆ SHFELRVGTITLHFDN ┆ SAGGSAGGSAGGSHFE │
│ .pdb              ┆ 6.pdb            ┆          ┆          ┆ ISEELAEELEKLAK…  ┆ LRVGTITLHFDNIS…  │
│ EA|run3_1140_0005 ┆ EA|run3_1140_000 ┆ 3.926922 ┆ wt       ┆ FHVTIHVGDITFHIHG ┆ SAGGSAGGSAGGFHVT │
│ .pdb              ┆ 5.pdb            ┆          ┆          ┆ VSEEEVKKLEELVR…  ┆ IHVGDITFHIHGVS…  │
│ EA|run5_0050_0004 ┆ EA|run5_0050_000 ┆ 4.381241 ┆ wt       ┆ TEVDLHLGDITIKLKD ┆ SAGGSAGGSAGGTEVD │
│ .pdb              ┆ 4.pdb            ┆          ┆          ┆ VSEEIVKRAKELFK…  ┆ LHLGDITIKLKDVS…  │
│ …                 ┆ …                ┆ …        ┆ …        ┆ …                ┆ …                │
│ 2KT8.pdb          ┆ 2KT8.pdb         ┆ 5.364639 ┆ wt       ┆ AEKTGIVNVSSSLNVR ┆ SAGGSAAEKTGIVNVS │
│                   ┆                  ┆          ┆          ┆ EGASTSSKVIGSLS…  ┆ SSLNVREGASTSSK…  │
│ 2KRS.pdb          ┆ 2KRS.pdb         ┆ 6.64727  ┆ wt       ┆ MQGVVKVNSALNMRSG ┆ SAGGMQGVVKVNSALN │
│                   ┆                  ┆          ┆          ┆ PGSNYGVIGTLRNN…  ┆ MRSGPGSNYGVIGT…  │
│ 2KYB.pdb          ┆ 2KYB.pdb         ┆ 4.953675 ┆ wt       ┆ TGIVNVSSSLNVRSSA ┆ SAGGSAGGSAGTGIVN │
│                   ┆                  ┆          ┆          ┆ STSSKVIGSLSGNT…  ┆ VSSSLNVRSSASTS…  │
│ XX|run8_1203_0001 ┆ XX|run8_1203_000 ┆ 5.24191  ┆ wt       ┆ SKIRITWGDKTWEWDG ┆ SAGGSAGGSAGGSKIR │
│ .pdb              ┆ 1.pdb            ┆          ┆          ┆ DDEEVWKRILEWAR…  ┆ ITWGDKTWEWDGDD…  │
│ r14_263_TrROS_Hal ┆ r14_263_TrROS_Ha ┆ 5.05123  ┆ wt       ┆ MRIRIEVETRTGPDGR ┆ SAMRIRIEVETRTGPD │
│ l.pdb             ┆ ll.pdb           ┆          ┆          ┆ KYVVVRIRDEKTGE…  ┆ GRKYVVVRIRDEKT…  │
└───────────────────┴──────────────────┴──────────┴──────────┴──────────────────┴──────────────────┘

In [4]:
df_wt = df_wt.select(['name', 'mutated_seq_full', 'deltaG'])

df_wt = df_wt.rename(
    {
        'mutated_seq_full': 'original_seq_full',
    }
)

df = df.filter(pl.col('name') != pl.col('WT_name')).filter(pl.col('mut_type') != 'wild_type')

df_wt

shape: (477, 3)
┌────────────────────────┬─────────────────────────────────┬──────────┐
│ name                   ┆ original_seq_full               ┆ deltaG   │
│ ---                    ┆ ---                             ┆ ---      │
│ str                    ┆ str                             ┆ f64      │
╞════════════════════════╪═════════════════════════════════╪══════════╡
│ EA|run2_0325_0005.pdb  ┆ SAGGSAGGSAGGDEVTIHLGDKTIRVDGLD… ┆ 3.332126 │
│ EA|run3_0321_0005.pdb  ┆ SAGGSAGGSAGGHDVTIHAGDKTIHVHGAS… ┆ 3.322303 │
│ EA|run3_0525_0006.pdb  ┆ SAGGSAGGSAGGSHFELRVGTITLHFDNIS… ┆ 3.717377 │
│ EA|run3_1140_0005.pdb  ┆ SAGGSAGGSAGGFHVTIHVGDITFHIHGVS… ┆ 3.926922 │
│ EA|run5_0050_0004.pdb  ┆ SAGGSAGGSAGGTEVDLHLGDITIKLKDVS… ┆ 4.381241 │
│ …                      ┆ …                               ┆ …        │
│ 2KT8.pdb               ┆ SAGGSAAEKTGIVNVSSSLNVREGASTSSK… ┆ 5.364639 │
│ 2KRS.pdb               ┆ SAGGMQGVVKVNSALNMRSGPGSNYGVIGT… ┆ 6.64727  │
│ 2KYB.pdb               ┆ SAGGSAGGSAGTGIVNVSSSLNVRSSASTS… ┆ 4.953675 │
│ XX|run8_1203_0001.pdb  ┆ SAGGSAGGSAGGSKIRITWGDKTWEWDGDD… ┆ 5.24191  │
│ r14_263_TrROS_Hall.pdb ┆ SAMRIRIEVETRTGPDGRKYVVVRIRDEKT… ┆ 5.05123  │
└────────────────────────┴─────────────────────────────────┴──────────┘

In [5]:

# df_joined = df_not_wt.join(df_wt, left_on='WT_name', right_on='name', how='left', suffix='_wt')
df_joined = df_not_wt.join(df_wt, left_on='original_seq_full', right_on='original_seq_full', how='left', suffix='_wt')

# group by mut_type and avg the dg
df_joined = df_joined.group_by("mutated_seq_full").agg(
    pl.col("deltaG").mean().alias("deltaG"),
    pl.col("deltaG_wt").mean().alias("deltaG_wt"),
    pl.col("original_seq_full").first().alias("original_seq_full"),
    #  pl.col("original_seq_full_wt").first().alias("original_seq_full_wt"),
    pl.col("mut_type").first().alias("mut_type"),
)

df_joined = df_joined.with_columns(
    (pl.col('deltaG') - pl.col('deltaG_wt')).alias('ddG')
)

df_joined.drop_nulls(subset=['ddG'])

df_joined = df_joined.select([

    # 'original_seq_full_wt',

    'original_seq_full', 'mutated_seq_full', 'deltaG', 'deltaG_wt', 'ddG', 'mut_type'
])

df_joined = df_joined.drop_nulls(["ddG"])
df_joined = df_joined.filter(pl.col('original_seq_full') != '-')


# reverse mutation
df_joined = df_joined.with_columns(pl.lit(False).alias("reverse"))

# Reverzní mutace
df_joined_with_reverse = df_joined.with_columns([
    pl.col("original_seq_full").alias("mutated_seq_full"),
    pl.col("mutated_seq_full").alias("original_seq_full"),
    # multiply by -1
    pl.col("ddG") * -1,

    pl.lit(True).alias("reverse")
])

df_joined_with_reverse = pl.concat([df_joined, df_joined_with_reverse])

df_joined_with_reverse.write_csv("datasets/megascale_dataset_with_ddg.csv")

df_joined_with_reverse

shape: (833_828, 7)
┌────────────────────┬────────────────────┬──────────┬───────────┬───────────┬───────────┬─────────┐
│ original_seq_full  ┆ mutated_seq_full   ┆ deltaG   ┆ deltaG_wt ┆ ddG       ┆ mut_type  ┆ reverse │
│ ---                ┆ ---                ┆ ---      ┆ ---       ┆ ---       ┆ ---       ┆ ---     │
│ str                ┆ str                ┆ f64      ┆ f64       ┆ f64       ┆ str       ┆ bool    │
╞════════════════════╪════════════════════╪══════════╪═══════════╪═══════════╪═══════════╪═════════╡
│ SAGGTYTWNTKEEAKQAF ┆ SAGGTYTWNTKEEAKQAF ┆ 0.609712 ┆ 2.23667   ┆ -1.626958 ┆ R22P      ┆ false   │
│ KELLKEKRVPSN…      ┆ KELLKEKPVPSN…      ┆          ┆           ┆           ┆           ┆         │
│ SAGGSAGGSAGGHEITLH ┆ SAGGSAGGSAGGHEITLH ┆ 3.58818  ┆ 4.440977  ┆ -0.852797 ┆ R17T      ┆ false   │
│ INGRRVKLRFRD…      ┆ INGRRVKLRFTD…      ┆          ┆           ┆           ┆           ┆         │
│ SAGGSAGGSKDPKFEAAY ┆ SAGGSAGGSKDPKFEAAM ┆ 1.333048 ┆ 2.501842  ┆ -1.168794 ┆ Y9M:K24Q  ┆ false   │
│ DFPGSGSSSELP…      ┆ DFPGSGSSSELP…      ┆          ┆           ┆           ┆           ┆         │
│ SAGGNKASVVANQLIPIN ┆ SAGGNKASVVANQLIPIN ┆ 3.863437 ┆ 4.161053  ┆ -0.297616 ┆ K39N      ┆ false   │
│ TALTLIMMKAEV…      ┆ TALTLIMMKAEV…      ┆          ┆           ┆           ┆           ┆         │
│ SAGGSAGWVPTKREEKYG ┆ SAGGSAGWVPTKREEKYG ┆ 0.75604  ┆ 2.212657  ┆ -1.456617 ┆ D31M:T47G ┆ false   │
│ VAFYNYDARGAD…      ┆ VAFYNYDARGAD…      ┆          ┆           ┆           ┆           ┆         │
│ …                  ┆ …                  ┆ …        ┆ …         ┆ …         ┆ …         ┆ …       │
│ SAGGNQASVVANQLIPIN ┆ SAGGNQASVVANQLIPIN ┆ 7.052293 ┆ 6.031509  ┆ -1.020783 ┆ V26E      ┆ true    │
│ TALTLVMMRSEE…      ┆ TALTLVMMRSEV…      ┆          ┆           ┆           ┆           ┆         │
│ SAGGSAGGSAQGDIVVAL ┆ SAGGSAGGSAQGDIVVAL ┆ -1.42882 ┆ 3.932004  ┆ 5.360824  ┆ Y11E:Y54I ┆ true    │
│ YPEDGIHPDDLS…      ┆ YPYDGIHPDDLS…      ┆          ┆           ┆           ┆           ┆         │
│ SAGGSAGGMTYKLILNGK ┆ SAGGSAGGMTYKLILNGK ┆ 1.998289 ┆ 2.698998  ┆ 0.700709  ┆ D47K      ┆ true    │
│ TLKGETTTEAVD…      ┆ TLKGETTTEAVD…      ┆          ┆           ┆           ┆           ┆         │
│ GSQPHIGNTTFTFDNPEK ┆ GSQVHIGNTTFTFDNPEK ┆ 0.064962 ┆ 1.44601   ┆ 1.381048  ┆ V3P       ┆ true    │
│ AQKYAEKYAKKK…      ┆ AQKYAEKYAKKK…      ┆          ┆           ┆           ┆           ┆         │
│ SAGGSAGGMVQRGSKVRI ┆ SAGGSAGGMVQRGSKVRI ┆ 0.331714 ┆ 2.280799  ┆ 1.949085  ┆ E41P:K42M ┆ true    │
│ LRPESYWFQDVG…      ┆ LRPESYWFQDVG…      ┆          ┆           ┆           ┆           ┆         │
└────────────────────┴────────────────────┴──────────┴───────────┴───────────┴───────────┴─────────┘

In [6]:
# join back and campute ddg (just the difference)

# join WT_name to name in df_wt

df_joined = df_not_wt.join(df_wt, left_on='WT_name', right_on='name', how='left', suffix='_wt')
# df_joined = df_not_wt.join(df_wt, left_on='original_seq_full', right_on='original_seq_full', how='left', suffix='_wt')


# group by mut_type and avg the dg
df_joined = df_joined.group_by("mutated_seq_full").agg(
    pl.col("deltaG").mean().alias("deltaG"),
    pl.col("deltaG_wt").mean().alias("deltaG_wt"),
    pl.col("original_seq_full").first().alias("original_seq_full"),
    pl.col("original_seq_full_wt").first().alias("original_seq_full_wt"),
    pl.col("mut_type").first().alias("mut_type"),
)

df_joined = df_joined.with_columns(
    (pl.col('deltaG') - pl.col('deltaG_wt')).alias('ddG')
)

df_joined.drop_nulls(subset=['ddG'])

df_joined = df_joined.select([

    'original_seq_full_wt',
    'original_seq_full', 'mutated_seq_full', 'deltaG', 'deltaG_wt', 'ddG', 'mut_type'
])

df_joined.filter(pl.col('mut_type') != 'wild_type').filter(
    pl.col('original_seq_full_wt') == pl.col('original_seq_full'))

df_joined = df_joined.drop_nulls(["ddG"])
df_joined = df_joined.filter(pl.col('original_seq_full') != '-')


df_joined

shape: (682_353, 7)
┌─────────────────┬────────────────┬────────────────┬──────────┬───────────┬───────────┬───────────┐
│ original_seq_fu ┆ original_seq_f ┆ mutated_seq_fu ┆ deltaG   ┆ deltaG_wt ┆ ddG       ┆ mut_type  │
│ ll_wt           ┆ ull            ┆ ll             ┆ ---      ┆ ---       ┆ ---       ┆ ---       │
│ ---             ┆ ---            ┆ ---            ┆ f64      ┆ f64       ┆ f64       ┆ str       │
│ str             ┆ str            ┆ str            ┆          ┆           ┆           ┆           │
╞═════════════════╪════════════════╪════════════════╪══════════╪═══════════╪═══════════╪═══════════╡
│ SAGGSPAHPYDRLKT ┆ SAGGSPAHPYDRLK ┆ SAGGSPAHPYDRLK ┆ 0.611124 ┆ 1.254028  ┆ -0.642904 ┆ E25G:Y45W │
│ TSTDPVSDIDVTRRE ┆ TTSTDPVSDIDVTR ┆ TTSTDPVSDIDVTR ┆          ┆           ┆           ┆           │
│ …               ┆ RE…            ┆ RG…            ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAGGYNL ┆ SAGGSAGGYNLQKL ┆ SAGGSAGGYNLQKL ┆ -0.00611 ┆ 2.057796  ┆ -2.063906 ┆ E24G:R46S │
│ QKLLAPYHKAKTLER ┆ LAPYHKAKTLERQV ┆ LAPYHKAKTLERQV ┆          ┆           ┆           ┆           │
│ …               ┆ YE…            ┆ YE…            ┆          ┆           ┆           ┆           │
│ GGSQTQRTQDENEAR ┆ GGSQTQRTQDENEA ┆ GGSQTQRTQDENEA ┆ 2.468309 ┆ 2.827459  ┆ -0.35915  ┆ R29A      │
│ RIAEEWKRRGYDVEV ┆ RRIAEEWKRRGYDV ┆ RRIAEEWKRRGYDV ┆          ┆           ┆           ┆           │
│ …               ┆ EV…            ┆ EV…            ┆          ┆           ┆           ┆           │
│ SAGGMIINNLKLIRE ┆ SAGGSAGGMIINNL ┆ SAGGSAGGMIINNL ┆ 2.025331 ┆ 3.380225  ┆ -1.354895 ┆ Q17C      │
│ KKKISQSELAALLES ┆ KLIREKKKISQSEL ┆ KLIREKKKISCSEL ┆          ┆           ┆           ┆           │
│ …               ┆ AA…            ┆ AA…            ┆          ┆           ┆           ┆           │
│ NNDALSPAIRRLLAE ┆ NNDALSPAIRRLLA ┆ NNIALSPAIRRLLA ┆ 2.759837 ┆ 2.996319  ┆ -0.236482 ┆ D3I       │
│ HNLDASAIKGTGVGG ┆ EHNLDASAIKGTGV ┆ EHNLDASAIKGTGV ┆          ┆           ┆           ┆           │
│ …               ┆ GG…            ┆ GG…            ┆          ┆           ┆           ┆           │
│ …               ┆ …              ┆ …              ┆ …        ┆ …         ┆ …         ┆ …         │
│ SAGGSAGGSAGGTTY ┆ SAGGSAGGSAGGTT ┆ SAGGSAGGSAGGTT ┆ -0.78508 ┆ 5.632582  ┆ -6.417662 ┆ L5G:F30T  │
│ KLILNGKTLKGETTT ┆ YKLILNGKTLKGET ┆ YKGILNGKTLKGET ┆          ┆           ┆           ┆           │
│ …               ┆ TT…            ┆ TT…            ┆          ┆           ┆           ┆           │
│ SAGGSMIINNLKLIR ┆ SAGGSMIINNLKLI ┆ SAGGSMIINNLKEI ┆ 3.80393  ┆ 3.82955   ┆ -0.02562  ┆ L8E       │
│ EKKKISQSELAALLE ┆ REKKKISQSELAAL ┆ REKKKISQSELAAL ┆          ┆           ┆           ┆           │
│ …               ┆ LE…            ┆ LE…            ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAGGSAG ┆ SAGGSAGGSAGGSA ┆ SAGGSAGGSAGGSA ┆ 0.481303 ┆ 2.215058  ┆ -1.733755 ┆ R9W:E29F  │
│ GMISNAKIARINELA ┆ GGMISNAKIARINE ┆ GGMISNAKIAWINE ┆          ┆           ┆           ┆           │
│ …               ┆ LA…            ┆ LA…            ┆          ┆           ┆           ┆           │
│ SAGGSASEEEIREAF ┆ SAGGSASEEEIREA ┆ SAGGSASEEEIREA ┆ 3.50002  ┆ 3.542207  ┆ -0.042187 ┆ Q55C      │
│ RVFDKDGNGYISAAD ┆ FRVFDKDGNGYISA ┆ FRVFDKDGNGYISA ┆          ┆           ┆           ┆           │
│ …               ┆ AD…            ┆ AD…            ┆          ┆           ┆           ┆           │
│ SQNEKLANELKSLLD ┆ SQNEKLANELKSLL ┆ SQNEKLANELKSLL ┆ 0.843959 ┆ 2.345188  ┆ -1.501229 ┆ K40G      │
│ ELNVNELATGSLNTY ┆ DELNVNELATGSLN ┆ DELNVNELATGSLN ┆          ┆           ┆           ┆           │
│ …               ┆ TY…            ┆ TY…            ┆          ┆           ┆           ┆           │
└─────────────────┴────────────────┴────────────────┴──────────┴───────────┴───────────┴───────────┘

In [8]:
df_joined_with_reverse.filter(pl.col('original_seq_full') == pl.col('mutated_seq_full'))

# df_joined_with_reverse.filter(pl.col('mut_type').str.contains(":")).filter(pl.col('original_seq_full') == pl.col('mutated_seq_full'))

shape: (0, 7)
┌───────────────────┬──────────────────┬────────┬───────────┬─────┬──────────┬─────────┐
│ original_seq_full ┆ mutated_seq_full ┆ deltaG ┆ deltaG_wt ┆ ddG ┆ mut_type ┆ reverse │
│ ---               ┆ ---              ┆ ---    ┆ ---       ┆ --- ┆ ---      ┆ ---     │
│ str               ┆ str              ┆ f64    ┆ f64       ┆ f64 ┆ str      ┆ bool    │
╞═══════════════════╪══════════════════╪════════╪═══════════╪═════╪══════════╪═════════╡
└───────────────────┴──────────────────┴────────┴───────────┴─────┴──────────┴─────────┘