In [162]:
import polars as pl

df = pl.read_csv(
    "../data/megascale.csv",
    null_values=["NA"],
    infer_schema_length=10000
)

columns_to_convert = ['dG_ML', 'ddG_ML']

df = df.with_columns(
    pl.col(columns_to_convert)
    .str.replace_all(r"[^0-9.-]", "")
    .cast(pl.Float64, strict=False)
)

df = df.select([
    "WT_name",
    "name",
    "deltaG",
    "mut_type",
    "aa_seq",
    "aa_seq_full",
])

df = df.rename(
    {
        'aa_seq': 'mutated_seq_short',
        'aa_seq_full': 'mutated_seq_full'
    })

df

shape: (776_298, 6)
┌──────────────────┬──────────────────┬───────────┬───────────┬──────────────────┬─────────────────┐
│ WT_name          ┆ name             ┆ deltaG    ┆ mut_type  ┆ mutated_seq_shor ┆ mutated_seq_ful │
│ ---              ┆ ---              ┆ ---       ┆ ---       ┆ t                ┆ l               │
│ str              ┆ str              ┆ f64       ┆ str       ┆ ---              ┆ ---             │
│                  ┆                  ┆           ┆           ┆ str              ┆ str             │
╞══════════════════╪══════════════════╪═══════════╪═══════════╪══════════════════╪═════════════════╡
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 3.332126  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEV │
│ 5.pdb            ┆ 5.pdb            ┆           ┆           ┆ LDKELLEILKELAR…  ┆ TIHLGDKTIRVDGLD │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 3.399832  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEV │
│ 5.pdb            ┆ 5.pdb_wtm        ┆           ┆           ┆ LDKELLEILKELAR…  ┆ TIHLGDKTIRVDGLD │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 3.315782  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEV │
│ 5.pdb            ┆ 5.pdb_wte        ┆           ┆           ┆ LDKELLEILKELAR…  ┆ TIHLGDKTIRVDGLD │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 3.272933  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEV │
│ 5.pdb            ┆ 5.pdb_wty        ┆           ┆           ┆ LDKELLEILKELAR…  ┆ TIHLGDKTIRVDGLD │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ 2.570242  ┆ wt        ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGSAG │
│ 5.pdb            ┆ 5.pdb_wth        ┆           ┆           ┆ LDKELLEILKELAR…  ┆ GDEVTIHLGDKTIRV │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ …                ┆ …                ┆ …         ┆ …         ┆ …                ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -2.85014  ┆ I32P:L40I ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -3.924992 ┆ I32P:L40W ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -2.365774 ┆ I32P:L40Y ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -1.961486 ┆ I32P:L40F ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
│ 9AME.pdb         ┆ 9AME.pdb_dmutv5_ ┆ -2.050294 ┆ I32P:L40P ┆ NQASVVANQLIPINTA ┆ SAGGSAGGNQASVVA │
│                  ┆ 32I:40L_I32P:L…  ┆           ┆           ┆ LTLVMMRSEVVTPV…  ┆ NQLIPINTALTLVMM │
│                  ┆                  ┆           ┆           ┆                  ┆ …               │
└──────────────────┴──────────────────┴───────────┴───────────┴──────────────────┴─────────────────┘

In [163]:
import polars as pl
import re
import polars as pl

df_not_wt = df.filter(pl.col('mut_type') != "wt")


def generate_mutated_sequence_full(mutated_seq_short, mut_type: str, mutated_seq_full: str) -> str:
    # Pokud je typ mutace 'wt' nebo podobný, vrátíme původní sekvenci beze změny
    if not mut_type or "wt" in mut_type.lower():
        return "-"

    original_seq = mutated_seq_full

    # find the starting index of original_seq in aa_seq_full
    index_offset = mutated_seq_full.find(mutated_seq_short)

    if ":" in mut_type:
        for i in mut_type.split(":"):
            match = re.match(r"([A-Z])(\d+)([A-Z])", i)

            if not match:
                return "-"

            original_aa, position_str, new_aa = match.groups()
            position = int(position_str)

            index = position - 1 + index_offset

            original_seq = original_seq[:index] + original_aa + original_seq[index + 1:]
        return original_seq

    match = re.match(r"([A-Z])(\d+)([A-Z])", mut_type)

    if not match:
        return "-"

    original_aa, position_str, new_aa = match.groups()
    position = int(position_str)

    index = position - 1 + index_offset

    original_seq = mutated_seq_full[:index] + original_aa + mutated_seq_full[index + 1:]

    return original_seq


df_not_wt = df_not_wt.with_columns(
    pl.struct(['mut_type', 'mutated_seq_full', "mutated_seq_short"])
    .map_elements(
        lambda row: generate_mutated_sequence_full(row['mutated_seq_short'], row['mut_type'], row['mutated_seq_full']),
        return_dtype=pl.String)
    # Výsledek uložíme do nového sloupce 'mutated_seq'
    .alias('original_seq_full'),

)

df_not_wt = df_not_wt.select(['name', 'WT_name', 'mut_type', 'mutated_seq_full', 'original_seq_full', "deltaG"])

# Přejmenování sloupce 'aa_seq' pro lepší srozumitelnost

df_not_wt

shape: (773_950, 6)
┌──────────────────┬──────────────────┬───────────┬──────────────────┬─────────────────┬───────────┐
│ name             ┆ WT_name          ┆ mut_type  ┆ mutated_seq_full ┆ original_seq_fu ┆ deltaG    │
│ ---              ┆ ---              ┆ ---       ┆ ---              ┆ ll              ┆ ---       │
│ str              ┆ str              ┆ str       ┆ str              ┆ ---             ┆ f64       │
│                  ┆                  ┆           ┆                  ┆ str             ┆           │
╞══════════════════╪══════════════════╪═══════════╪══════════════════╪═════════════════╪═══════════╡
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ D1Q       ┆ SAGGSAGGSAGGQEVT ┆ SAGGSAGGSAGGDEV ┆ 3.242632  │
│ 5.pdb_D1Q        ┆ 5.pdb            ┆           ┆ IHLGDKTIRVDGLD…  ┆ TIHLGDKTIRVDGLD ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ D1E       ┆ SAGGSAGGSAGGEEVT ┆ SAGGSAGGSAGGDEV ┆ 3.247267  │
│ 5.pdb_D1E        ┆ 5.pdb            ┆           ┆ IHLGDKTIRVDGLD…  ┆ TIHLGDKTIRVDGLD ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ D1N       ┆ SAGGSAGGSAGGNEVT ┆ SAGGSAGGSAGGDEV ┆ 3.269113  │
│ 5.pdb_D1N        ┆ 5.pdb            ┆           ┆ IHLGDKTIRVDGLD…  ┆ TIHLGDKTIRVDGLD ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ D1H       ┆ SAGGSAGGSAGGHEVT ┆ SAGGSAGGSAGGDEV ┆ 3.234823  │
│ 5.pdb_D1H        ┆ 5.pdb            ┆           ┆ IHLGDKTIRVDGLD…  ┆ TIHLGDKTIRVDGLD ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
│ EA|run2_0325_000 ┆ EA|run2_0325_000 ┆ D1R       ┆ SAGGSAGGSAGGREVT ┆ SAGGSAGGSAGGDEV ┆ 2.912039  │
│ 5.pdb_D1R        ┆ 5.pdb            ┆           ┆ IHLGDKTIRVDGLD…  ┆ TIHLGDKTIRVDGLD ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
│ …                ┆ …                ┆ …         ┆ …                ┆ …               ┆ …         │
│ 9AME.pdb_dmutv5_ ┆ 9AME.pdb         ┆ I32P:L40I ┆ SAGGSAGGNQASVVAN ┆ SAGGSAGGNQASVVA ┆ -2.85014  │
│ 32I:40L_I32P:L…  ┆                  ┆           ┆ QLIPINTALTLVMM…  ┆ NQLIPINTALTLVMM ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
│ 9AME.pdb_dmutv5_ ┆ 9AME.pdb         ┆ I32P:L40W ┆ SAGGSAGGNQASVVAN ┆ SAGGSAGGNQASVVA ┆ -3.924992 │
│ 32I:40L_I32P:L…  ┆                  ┆           ┆ QLIPINTALTLVMM…  ┆ NQLIPINTALTLVMM ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
│ 9AME.pdb_dmutv5_ ┆ 9AME.pdb         ┆ I32P:L40Y ┆ SAGGSAGGNQASVVAN ┆ SAGGSAGGNQASVVA ┆ -2.365774 │
│ 32I:40L_I32P:L…  ┆                  ┆           ┆ QLIPINTALTLVMM…  ┆ NQLIPINTALTLVMM ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
│ 9AME.pdb_dmutv5_ ┆ 9AME.pdb         ┆ I32P:L40F ┆ SAGGSAGGNQASVVAN ┆ SAGGSAGGNQASVVA ┆ -1.961486 │
│ 32I:40L_I32P:L…  ┆                  ┆           ┆ QLIPINTALTLVMM…  ┆ NQLIPINTALTLVMM ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
│ 9AME.pdb_dmutv5_ ┆ 9AME.pdb         ┆ I32P:L40P ┆ SAGGSAGGNQASVVAN ┆ SAGGSAGGNQASVVA ┆ -2.050294 │
│ 32I:40L_I32P:L…  ┆                  ┆           ┆ QLIPINTALTLVMM…  ┆ NQLIPINTALTLVMM ┆           │
│                  ┆                  ┆           ┆                  ┆ …               ┆           │
└──────────────────┴──────────────────┴───────────┴──────────────────┴─────────────────┴───────────┘

In [164]:
df_wt = df.filter(pl.col('name') == pl.col('WT_name')).filter(pl.col('mut_type') == 'wt')
df_wt

shape: (477, 6)
┌───────────────────┬──────────────────┬──────────┬──────────┬──────────────────┬──────────────────┐
│ WT_name           ┆ name             ┆ deltaG   ┆ mut_type ┆ mutated_seq_shor ┆ mutated_seq_full │
│ ---               ┆ ---              ┆ ---      ┆ ---      ┆ t                ┆ ---              │
│ str               ┆ str              ┆ f64      ┆ str      ┆ ---              ┆ str              │
│                   ┆                  ┆          ┆          ┆ str              ┆                  │
╞═══════════════════╪══════════════════╪══════════╪══════════╪══════════════════╪══════════════════╡
│ EA|run2_0325_0005 ┆ EA|run2_0325_000 ┆ 3.332126 ┆ wt       ┆ DEVTIHLGDKTIRVDG ┆ SAGGSAGGSAGGDEVT │
│ .pdb              ┆ 5.pdb            ┆          ┆          ┆ LDKELLEILKELAR…  ┆ IHLGDKTIRVDGLD…  │
│ EA|run3_0321_0005 ┆ EA|run3_0321_000 ┆ 3.322303 ┆ wt       ┆ HDVTIHAGDKTIHVHG ┆ SAGGSAGGSAGGHDVT │
│ .pdb              ┆ 5.pdb            ┆          ┆          ┆ ASEEFLRIIEQAKR…  ┆ IHAGDKTIHVHGAS…  │
│ EA|run3_0525_0006 ┆ EA|run3_0525_000 ┆ 3.717377 ┆ wt       ┆ SHFELRVGTITLHFDN ┆ SAGGSAGGSAGGSHFE │
│ .pdb              ┆ 6.pdb            ┆          ┆          ┆ ISEELAEELEKLAK…  ┆ LRVGTITLHFDNIS…  │
│ EA|run3_1140_0005 ┆ EA|run3_1140_000 ┆ 3.926922 ┆ wt       ┆ FHVTIHVGDITFHIHG ┆ SAGGSAGGSAGGFHVT │
│ .pdb              ┆ 5.pdb            ┆          ┆          ┆ VSEEEVKKLEELVR…  ┆ IHVGDITFHIHGVS…  │
│ EA|run5_0050_0004 ┆ EA|run5_0050_000 ┆ 4.381241 ┆ wt       ┆ TEVDLHLGDITIKLKD ┆ SAGGSAGGSAGGTEVD │
│ .pdb              ┆ 4.pdb            ┆          ┆          ┆ VSEEIVKRAKELFK…  ┆ LHLGDITIKLKDVS…  │
│ …                 ┆ …                ┆ …        ┆ …        ┆ …                ┆ …                │
│ 2KT8.pdb          ┆ 2KT8.pdb         ┆ 5.364639 ┆ wt       ┆ AEKTGIVNVSSSLNVR ┆ SAGGSAAEKTGIVNVS │
│                   ┆                  ┆          ┆          ┆ EGASTSSKVIGSLS…  ┆ SSLNVREGASTSSK…  │
│ 2KRS.pdb          ┆ 2KRS.pdb         ┆ 6.64727  ┆ wt       ┆ MQGVVKVNSALNMRSG ┆ SAGGMQGVVKVNSALN │
│                   ┆                  ┆          ┆          ┆ PGSNYGVIGTLRNN…  ┆ MRSGPGSNYGVIGT…  │
│ 2KYB.pdb          ┆ 2KYB.pdb         ┆ 4.953675 ┆ wt       ┆ TGIVNVSSSLNVRSSA ┆ SAGGSAGGSAGTGIVN │
│                   ┆                  ┆          ┆          ┆ STSSKVIGSLSGNT…  ┆ VSSSLNVRSSASTS…  │
│ XX|run8_1203_0001 ┆ XX|run8_1203_000 ┆ 5.24191  ┆ wt       ┆ SKIRITWGDKTWEWDG ┆ SAGGSAGGSAGGSKIR │
│ .pdb              ┆ 1.pdb            ┆          ┆          ┆ DDEEVWKRILEWAR…  ┆ ITWGDKTWEWDGDD…  │
│ r14_263_TrROS_Hal ┆ r14_263_TrROS_Ha ┆ 5.05123  ┆ wt       ┆ MRIRIEVETRTGPDGR ┆ SAMRIRIEVETRTGPD │
│ l.pdb             ┆ ll.pdb           ┆          ┆          ┆ KYVVVRIRDEKTGE…  ┆ GRKYVVVRIRDEKT…  │
└───────────────────┴──────────────────┴──────────┴──────────┴──────────────────┴──────────────────┘

In [165]:
df_wt = df_wt.select(['name', 'mutated_seq_full', 'deltaG'])

df_wt = df_wt.rename(
    {
        'mutated_seq_full': 'original_seq_full',
    }
)

df = df.filter(pl.col('name') != pl.col('WT_name')).filter(pl.col('mut_type') != 'wild_type')

df_wt

shape: (477, 3)
┌────────────────────────┬─────────────────────────────────┬──────────┐
│ name                   ┆ original_seq_full               ┆ deltaG   │
│ ---                    ┆ ---                             ┆ ---      │
│ str                    ┆ str                             ┆ f64      │
╞════════════════════════╪═════════════════════════════════╪══════════╡
│ EA|run2_0325_0005.pdb  ┆ SAGGSAGGSAGGDEVTIHLGDKTIRVDGLD… ┆ 3.332126 │
│ EA|run3_0321_0005.pdb  ┆ SAGGSAGGSAGGHDVTIHAGDKTIHVHGAS… ┆ 3.322303 │
│ EA|run3_0525_0006.pdb  ┆ SAGGSAGGSAGGSHFELRVGTITLHFDNIS… ┆ 3.717377 │
│ EA|run3_1140_0005.pdb  ┆ SAGGSAGGSAGGFHVTIHVGDITFHIHGVS… ┆ 3.926922 │
│ EA|run5_0050_0004.pdb  ┆ SAGGSAGGSAGGTEVDLHLGDITIKLKDVS… ┆ 4.381241 │
│ …                      ┆ …                               ┆ …        │
│ 2KT8.pdb               ┆ SAGGSAAEKTGIVNVSSSLNVREGASTSSK… ┆ 5.364639 │
│ 2KRS.pdb               ┆ SAGGMQGVVKVNSALNMRSGPGSNYGVIGT… ┆ 6.64727  │
│ 2KYB.pdb               ┆ SAGGSAGGSAGTGIVNVSSSLNVRSSASTS… ┆ 4.953675 │
│ XX|run8_1203_0001.pdb  ┆ SAGGSAGGSAGGSKIRITWGDKTWEWDGDD… ┆ 5.24191  │
│ r14_263_TrROS_Hall.pdb ┆ SAMRIRIEVETRTGPDGRKYVVVRIRDEKT… ┆ 5.05123  │
└────────────────────────┴─────────────────────────────────┴──────────┘

In [179]:

# df_joined = df_not_wt.join(df_wt, left_on='WT_name', right_on='name', how='left', suffix='_wt')
df_joined = df_not_wt.join(df_wt, left_on='original_seq_full', right_on='original_seq_full', how='left', suffix='_wt')

# group by mut_type and avg the dg
df_joined = df_joined.group_by("mutated_seq_full").agg(
    pl.col("deltaG").mean().alias("deltaG"),
    pl.col("deltaG_wt").mean().alias("deltaG_wt"),
    pl.col("original_seq_full").first().alias("original_seq_full"),
    #  pl.col("original_seq_full_wt").first().alias("original_seq_full_wt"),
    pl.col("mut_type").first().alias("mut_type"),
)

df_joined = df_joined.with_columns(
    (pl.col('deltaG') - pl.col('deltaG_wt')).alias('ddG')
)

df_joined.drop_nulls(subset=['ddG'])

df_joined = df_joined.select([

    # 'original_seq_full_wt',

    'original_seq_full', 'mutated_seq_full', 'deltaG', 'deltaG_wt', 'ddG', 'mut_type'
])

df_joined = df_joined.drop_nulls(["ddG"])
df_joined = df_joined.filter(pl.col('original_seq_full') != '-')

df_joined.write_csv("megascale_dataset_with_ddg.csv")

df_joined

shape: (417_051, 6)
┌─────────────────────────┬─────────────────────────┬──────────┬───────────┬───────────┬───────────┐
│ original_seq_full       ┆ mutated_seq_full        ┆ deltaG   ┆ deltaG_wt ┆ ddG       ┆ mut_type  │
│ ---                     ┆ ---                     ┆ ---      ┆ ---       ┆ ---       ┆ ---       │
│ str                     ┆ str                     ┆ f64      ┆ f64       ┆ f64       ┆ str       │
╞═════════════════════════╪═════════════════════════╪══════════╪═══════════╪═══════════╪═══════════╡
│ SAGGSAGGSAGGVKKMAKAIMAD ┆ SAGGSAGGSAGGVKKMAKAIMHD ┆ 1.73325  ┆ 2.118488  ┆ -0.385238 ┆ A10H      │
│ PNKADEV…                ┆ PNKADEV…                ┆          ┆           ┆           ┆           │
│ GTEDEKKIQELLKRANGDVSKAE ┆ GTEDEKKIQELLKRANGDVSKAE ┆ 1.31248  ┆ 2.150429  ┆ -0.837949 ┆ Q26G      │
│ KLAQSQG…                ┆ KLAGSQG…                ┆          ┆           ┆           ┆           │
│ SAGGSAMAMNGTITTWFKDKGFG ┆ SAGGSAMAMNGTITTWFKDKGFG ┆ 4.293293 ┆ 4.094748  ┆ 0.198545  ┆ K55C      │
│ FIKDENG…                ┆ FIKDENG…                ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAGKRYRAVYDYSAA ┆ SAGGSAGGSAGKRYRAVYDYSAA ┆ 3.398878 ┆ 3.067643  ┆ 0.331235  ┆ N27V:T39T │
│ DEDEVSF…                ┆ DEDEVSF…                ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAGGFHVTIHVGDIT ┆ SAGGSAGGSAGGFTVTIHVGDIT ┆ 4.68647  ┆ 3.926922  ┆ 0.759548  ┆ H2T       │
│ FHIHGVS…                ┆ FHIHGVS…                ┆          ┆           ┆           ┆           │
│ …                       ┆ …                       ┆ …        ┆ …         ┆ …         ┆ …         │
│ SSGGSSILDRAVIEHNLLSASKL ┆ SSGGSSILDRAVIEHNLLSASKL ┆ 3.094963 ┆ 3.280557  ┆ -0.185594 ┆ S48E      │
│ YNNITFE…                ┆ YNNITFE…                ┆          ┆           ┆           ┆           │
│ SAGGSAGYKIYPYDSLIVTNSIS ┆ SAGGSAGYKIYKYDSLIVTNSIS ┆ 2.720596 ┆ 3.837928  ┆ -1.117333 ┆ P5K       │
│ VKLPKDV…                ┆ VKLPKDV…                ┆          ┆           ┆           ┆           │
│ SAGGSAVTLFVALYDYEAITEDD ┆ SAGGSAVTLFVALYDYEDITEDD ┆ 1.956858 ┆ 5.028433  ┆ -3.071576 ┆ A12D      │
│ LSFHKGE…                ┆ LSFHKGE…                ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAGGVKKMAKAIMAD ┆ SAGGSAGGSAGGVKKMAKAIMAD ┆ 2.105359 ┆ 2.118488  ┆ -0.013129 ┆ D24S      │
│ PNKADEV…                ┆ PNKADEV…                ┆          ┆           ┆           ┆           │
│ GSEEELIEKAEKLRKEFEFIWNG ┆ GSEEELIEKAEKLRKEFEFIWNG ┆ 1.304867 ┆ 1.612551  ┆ -0.307684 ┆ L40V      │
│ IRFIIRE…                ┆ IRFIIRE…                ┆          ┆           ┆           ┆           │
└─────────────────────────┴─────────────────────────┴──────────┴───────────┴───────────┴───────────┘

In [177]:
# join back and campute ddg (just the difference)

# join WT_name to name in df_wt

df_joined = df_not_wt.join(df_wt, left_on='WT_name', right_on='name', how='left', suffix='_wt')
# df_joined = df_not_wt.join(df_wt, left_on='original_seq_full', right_on='original_seq_full', how='left', suffix='_wt')


# group by mut_type and avg the dg
df_joined = df_joined.group_by("mutated_seq_full").agg(
    pl.col("deltaG").mean().alias("deltaG"),
    pl.col("deltaG_wt").mean().alias("deltaG_wt"),
    pl.col("original_seq_full").first().alias("original_seq_full"),
    pl.col("original_seq_full_wt").first().alias("original_seq_full_wt"),
    pl.col("mut_type").first().alias("mut_type"),
)

df_joined = df_joined.with_columns(
    (pl.col('deltaG') - pl.col('deltaG_wt')).alias('ddG')
)

df_joined.drop_nulls(subset=['ddG'])

df_joined = df_joined.select([

    'original_seq_full_wt',
    'original_seq_full', 'mutated_seq_full', 'deltaG', 'deltaG_wt', 'ddG', 'mut_type'
])

df_joined.filter(pl.col('mut_type') != 'wild_type').filter(
    pl.col('original_seq_full_wt') == pl.col('original_seq_full'))

df_joined = df_joined.drop_nulls(["ddG"])
df_joined = df_joined.filter(pl.col('original_seq_full') != '-')


df_joined

shape: (682_534, 7)
┌─────────────────┬────────────────┬────────────────┬──────────┬───────────┬───────────┬───────────┐
│ original_seq_fu ┆ original_seq_f ┆ mutated_seq_fu ┆ deltaG   ┆ deltaG_wt ┆ ddG       ┆ mut_type  │
│ ll_wt           ┆ ull            ┆ ll             ┆ ---      ┆ ---       ┆ ---       ┆ ---       │
│ ---             ┆ ---            ┆ ---            ┆ f64      ┆ f64       ┆ f64       ┆ str       │
│ str             ┆ str            ┆ str            ┆          ┆           ┆           ┆           │
╞═════════════════╪════════════════╪════════════════╪══════════╪═══════════╪═══════════╪═══════════╡
│ SAGGNKASVVANQLI ┆ SAGGNKASVVANQL ┆ SAGGNKASVVANQL ┆ 3.88279  ┆ 4.161053  ┆ -0.278263 ┆ A48Q      │
│ PINTALTLIMMKAEV ┆ IPINTALTLIMMKA ┆ IPINTALTLIMMKA ┆          ┆           ┆           ┆           │
│ …               ┆ EV…            ┆ EV…            ┆          ┆           ┆           ┆           │
│ SAGGSAGGSMDETGK ┆ SAGGSMDETGKELV ┆ SAGGSMDETGKELV ┆ 4.041552 ┆ 3.930052  ┆ 0.111499  ┆ L10M      │
│ ELVLALYDYQEKSPR ┆ LALYDYQEKSPREV ┆ MALYDYQEKSPREV ┆          ┆           ┆           ┆           │
│ …               ┆ TM…            ┆ TM…            ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAVTTYK ┆ SAGGSAVTTYKLVI ┆ SAGGSAVTTYKLVI ┆ 5.270467 ┆ 5.200807  ┆ 0.069659  ┆ A24H      │
│ LVINGKTLKGETTTK ┆ NGKTLKGETTTKAV ┆ NGKTLKGETTTKAV ┆          ┆           ┆           ┆           │
│ …               ┆ DA…            ┆ DH…            ┆          ┆           ┆           ┆           │
│ SAGGMIINNLKLIRE ┆ SAGGMIINNLKLIR ┆ SAGGMIINNTKLIR ┆ 1.210061 ┆ 3.380225  ┆ -2.170165 ┆ L6T       │
│ KKKISQSELAALLES ┆ EKKKISQSELAALL ┆ EKKKISQSELAALL ┆          ┆           ┆           ┆           │
│ …               ┆ ES…            ┆ ES…            ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAGGMKV ┆ SAGGSAGGSAGGMK ┆ SAGGSAGGSAGGMK ┆ 3.349693 ┆ 3.410379  ┆ -0.060686 ┆ K45M      │
│ IFLKDVKGKGKKGEI ┆ VIFLKDVKGKGKKG ┆ VIFLKDVKGKGKKG ┆          ┆           ┆           ┆           │
│ …               ┆ EI…            ┆ EI…            ┆          ┆           ┆           ┆           │
│ …               ┆ …              ┆ …              ┆ …        ┆ …         ┆ …         ┆ …         │
│ SAGGMQGVVKVNSAL ┆ SAGGMQGVVKVNSA ┆ SAGGMQGVVKVNSA ┆ 0.753659 ┆ 2.44228   ┆ -1.688621 ┆ G18A      │
│ NMRSGPGSNYGVIGT ┆ LNMRSGPGSNYGVI ┆ LNMRSGPASNYGVI ┆          ┆           ┆           ┆           │
│ …               ┆ GT…            ┆ GT…            ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAMVIED ┆ SAGGSAGGSAMVIE ┆ SAGGSAGGSAMVIM ┆ 3.999067 ┆ 4.436625  ┆ -0.437559 ┆ E4M       │
│ PKTNKLIEVEKLPDG ┆ DPKTNKLIEVEKLP ┆ DPKTNKLIEVEKLP ┆          ┆           ┆           ┆           │
│ …               ┆ DG…            ┆ DG…            ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAGGSAG ┆ SAGGSAGGSAGGSA ┆ SAGGSAGGSAGGSA ┆ 1.704465 ┆ 1.642966  ┆ 0.061499  ┆ Q42H      │
│ TLDMDAVLSDFVRST ┆ GTLDMDAVLSDFVR ┆ GTLDMDAVLSDFVR ┆          ┆           ┆           ┆           │
│ …               ┆ ST…            ┆ ST…            ┆          ┆           ┆           ┆           │
│ SAGGSAGGSAGGSAE ┆ SAGGSAGGSAGGSA ┆ SAGGSAGGSAGGSA ┆ 0.231902 ┆ 1.381775  ┆ -1.149872 ┆ L24M      │
│ QLARLKREFNENRYL ┆ EQLARLKREFNENR ┆ EQLARLKREFNENR ┆          ┆           ┆           ┆           │
│ …               ┆ YL…            ┆ YL…            ┆          ┆           ┆           ┆           │
│ SAGGSAGGSADIIVV ┆ SAGGSAGGSADIIV ┆ SAGGSAGGSADIIV ┆ 2.0111   ┆ 4.385071  ┆ -2.373971 ┆ D24S:S40E │
│ ALYDYEAIHHEDLSF ┆ VALYDYEAIHHEDL ┆ VALYDYEAIHHEDL ┆          ┆           ┆           ┆           │
│ …               ┆ SF…            ┆ SF…            ┆          ┆           ┆           ┆           │
└─────────────────┴────────────────┴────────────────┴──────────┴───────────┴───────────┴───────────┘

shape: (217_457, 7)
┌────────────────┬────────────────┬────────────────┬───────────┬───────────┬───────────┬───────────┐
│ original_seq_f ┆ original_seq_f ┆ mutated_seq_fu ┆ deltaG    ┆ deltaG_wt ┆ ddG       ┆ mut_type  │
│ ull_wt         ┆ ull            ┆ ll             ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ ---            ┆ ---            ┆ ---            ┆ f64       ┆ f64       ┆ f64       ┆ str       │
│ str            ┆ str            ┆ str            ┆           ┆           ┆           ┆           │
╞════════════════╪════════════════╪════════════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SAGGSAGGMVQRGS ┆ SAGGSAGGMVQRGS ┆ SAGGSAGGMVQRGS ┆ -0.782446 ┆ 2.280799  ┆ -3.063245 ┆ F53F:L58K │
│ KVRILRPESYWFQD ┆ KVRILRPESYWFQD ┆ KVRILRPESYWFQD ┆           ┆           ┆           ┆           │
│ VG…            ┆ VG…            ┆ VG…            ┆           ┆           ┆           ┆           │
│ SAGGSEFTQISGYV ┆ SAGGSEFTQISGYV ┆ SAGGSEFTQISGYV ┆ -2.417792 ┆ 1.703911  ┆ -4.121703 ┆ F37N:V52L │
│ NAFGSQRGSVLTVK ┆ NAFGSQRGSVLTVK ┆ NAFGSQRGSVLTVK ┆           ┆           ┆           ┆           │
│ VE…            ┆ VE…            ┆ VE…            ┆           ┆           ┆           ┆           │
│ SAGGSAGGMATADD ┆ SAGGMATADDFKLI ┆ SAGGMATADDFKLI ┆ -0.802064 ┆ 4.083619  ┆ -4.885683 ┆ E32P:R42M │
│ FKLIRDIHSTGGRR ┆ RDIHSTGGRRQVFG ┆ RDIHSTGGRRQVFG ┆           ┆           ┆           ┆           │
│ QV…            ┆ SR…            ┆ SR…            ┆           ┆           ┆           ┆           │
│ SAGGSAGGMTYKLI ┆ SAGGSAGGMTYKLI ┆ SAGGSAGGMTYKLI ┆ 3.409993  ┆ 5.264723  ┆ -1.85473  ┆ D46S:T49A │
│ LNGKTLKGETTTEA ┆ LNGKTLKGETTTEA ┆ LNGKTLKGETTTEA ┆           ┆           ┆           ┆           │
│ VD…            ┆ VD…            ┆ VD…            ┆           ┆           ┆           ┆           │
│ SSGGSSILDRAVIE ┆ SSGGSSILDRAVIE ┆ SSGGSSILDRAVIE ┆ 0.553068  ┆ 3.280557  ┆ -2.727489 ┆ Q49P:R55Y │
│ HNLLSASKLYNNIT ┆ HNLLSASKLYNNIT ┆ HNLLSASKLYNNIT ┆           ┆           ┆           ┆           │
│ FE…            ┆ FE…            ┆ FE…            ┆           ┆           ┆           ┆           │
│ …              ┆ …              ┆ …              ┆ …         ┆ …         ┆ …         ┆ …         │
│ SASIVTKIISIVQE ┆ SASIVTKIISIVQE ┆ SASIVTKIISIVQE ┆ 2.768125  ┆ 3.288587  ┆ -0.520462 ┆ E43V:K53H │
│ RQNMDDGAPVKTRD ┆ RQNMDDGAPVKTRD ┆ RQNMDDGAPVKTRD ┆           ┆           ┆           ┆           │
│ IA…            ┆ IA…            ┆ IA…            ┆           ┆           ┆           ┆           │
│ SAGGSAGGSAGGKD ┆ SAGGSAGGSAGGKD ┆ SAGGSAGGSAGGKD ┆ -0.090566 ┆ 2.642788  ┆ -2.733354 ┆ H24H:W53R │
│ KDLLKGLDQEQANE ┆ KDLLKGLDQEQANE ┆ KDLLKGLDQEQANE ┆           ┆           ┆           ┆           │
│ VI…            ┆ VI…            ┆ VI…            ┆           ┆           ┆           ┆           │
│ SAGMEQGTVKWFNA ┆ SAGMEQGTVKWFNA ┆ SAGMEQGTVKWFNA ┆ 1.847002  ┆ 4.794167  ┆ -2.947165 ┆ H29T:S31V │
│ EKGFGFIERENGDD ┆ EKGFGFIERENGDD ┆ EKGFGFIERENGDD ┆           ┆           ┆           ┆           │
│ VF…            ┆ VF…            ┆ VF…            ┆           ┆           ┆           ┆           │
│ SAGGSAGGSAGKSA ┆ SAGGSAGKSAVKAL ┆ SAGGSAGKSAVKAL ┆ -0.208178 ┆ 3.042191  ┆ -3.250369 ┆ D40P:Q46A │
│ VKALFDYKAQREDE ┆ FDYKAQREDELTFT ┆ FDYKAQREDELTFT ┆           ┆           ┆           ┆           │
│ LT…            ┆ KS…            ┆ KS…            ┆           ┆           ┆           ┆           │
│ SAGGSAGGSAGGID ┆ SAGGSAGGIDAAQI ┆ SAGGSAGGIDAAQI ┆ 1.765067  ┆ 3.685447  ┆ -1.92038  ┆ E9G:K40Q  │
│ AAQIVDEALEQGIT ┆ VDEALEQGITLFVV ┆ VDGALEQGITLFVV ┆           ┆           ┆           ┆           │
│ LF…            ┆ NN…            ┆ NN…            ┆           ┆           ┆           ┆           │
└────────────────┴────────────────┴────────────────┴───────────┴───────────┴───────────┴───────────┘